### ISSUE TITLE
Notification list in the header

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/activity#10]
https://github.com/owncloud/core/issues/6348
> As a user i'd like to have a pop-up-notification-center similar to "Atlassian Confluence".
> The difference to the activity-stream would be:
> * it is available everywhere in owncloud
> * it shows not only a history / past events, but alerts me for present or future events/messages, etc.
> * it refreshes via ajax in the background. so i don't have to klick on "News" to check if there are unread news, i don't have to click "Calendar" to check if there are new events.
> There would be a small number (3) on the symbol in the top right corner and i can see directly if there are somethings todo etc.
> 
> Mockup:
> [mockup notification center](https://f.cloud.github.com/assets/4741199/1732973/34af59b2-632c-11e3-814f-64000cae8eee.png)

**Comment by jancborchardt** [comment]
To comment this (next time please do that @nickvergessen when you close an issue): We have a notifications app now: https://github.com/owncloud/notifications, which will be shipped with the upcoming 8.2
