### ISSUE TITLE
Activity when a share was unshared

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/activity#100]
- [x] Depends on owncloud/core#9761

**Comment by cmonteroluque** [comment]
No notification when a share in unshared seems like a bug to me

**Comment by MTRichards** [comment]
Yep, to me too. I think we have had it around before too, it sounds familiar. Perhaps when talking about the log file...same result is needed there too.

**Comment by cmonteroluque** [comment]
based on "Depends on owncloud/core#9058"

**Comment by nickvergessen** [comment]
Just as a comment:
> I think we have had it around before too, it sounds familiar.

We never had such activities,

**Comment by nickvergessen** [comment]
This is in for 9.0.0
