### ISSUE TITLE
Acceptance tests for renaming and moving activities

### ISSUE THREAD

**Issue by JammingBen** [owncloud/activity#1019]
https://github.com/owncloud/activity/pull/1018 and https://github.com/owncloud/core/pull/39430 introduce activities for rename- and move-actions. The following scenarios need acceptance test scenarios:

- [x] Rename file in root
- [x] Rename file in a subfolder
- [x] Move file into subfolder
- [x] Move folder out of subfolder
- [x] Rename a shared folder -> only affects the user who renames
- [x] Rename a file inside a shared folder -> affects all share users (**)
- [x] Move a file inside a shared folder into a subfolder inside the share -> affects all share users (**)
- [x] Move a file into the share -> affects all share users, but only the users who moves sees the source path (**)
- [x] Move a file out of a share -> affects all share users, but only the users who moves sees the destination path (**)

** also use "Shares" as default share folder

@phil-davis Could you and your team have a look at this?

**Comment by kiranparajuli589** [comment]
TODO: https://github.com/owncloud/activity/pull/1022#issuecomment-960667209

**Comment by phil-davis** [comment]
@kiranparajuli589 Last week I added a couple of scenarios for moving a file between shares (shares to users, and shares to groups).

Can you think of any other interesting test cases?

**Comment by kiranparajuli589** [comment]
TODO:
- [ ] check a public user action
- [ ] webui scenarios

**Comment by phil-davis** [comment]
@kiranparajuli589 the code PR has been merged, so you can branch from latest master to add more test scenarios.

**Comment by individual-it** [comment]
#1030 was merged, more tests needed?

**Comment by phil-davis** [comment]
We could just have 2 scenarios for an ordinary rename and move. (The actual rename and move can be done with the API or whatever is easiest) And demonstrate that the UI shows the activity entries with the expected rename/move words.

**Comment by phil-davis** [comment]
This should not be too difficult. @sushmita56 please add rename and move scenarios, then this issue can be closed.

**Comment by sushmita56** [comment]
@phil-davis The `Activity` tab on the UI doesn't show any notification regarding the moving/copying of the resource but it shows the information about the resource creation/deletion. Is this an expected behavior or should I report an issue
![Screenshot from 2022-05-18 11-50-51](https://user-images.githubusercontent.com/66173400/168969243-743aea22-bdb1-4167-9030-19f4924e1031.png)
?

**Comment by phil-davis** [comment]
@sushmita56 the feature has to be enabled:
```
php occ config:app:set activity enable_move_and_rename_activities --value yes
```

Then it works.

In Gherkin feature files hace a Given step like:
```
Given the administrator has added config key "enable_move_and_rename_activities" with value "yes" in app "activity"
```

**Comment by SwikritiT** [comment]
@phil-davis the PR for web-ui test has been merged. I guess it's safe to close this? Or do we need to add more tests?

**Comment by phil-davis** [comment]
done - closing
