### ISSUE TITLE
Activity when a public share has been downloaded

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/activity#103]
Copied from todo in the code

**Comment by jnfrmarks** [comment]
@schiesbn 

I don't see downloaded files in my activity stream.

Testing with:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-12T03:08:46+00:00 20d2d8d3ddee2750343bdec69a3e7031b710039a

**Comment by nickvergessen** [comment]
Note: this only works for public link shares. Just tested again and it works here:
![download-public-link](https://cloud.githubusercontent.com/assets/213943/7591745/da19d4ba-f8cf-11e4-966d-16ff8f6d214d.png)

**Comment by jnfrmarks** [comment]
@nickvergessen 

What is the expected behavior when downloading a file/folder?  Should the download show up in the activity stream?

**Comment by nickvergessen** [comment]
@jnfrmarks 
If a file is shared as public link and then someone downloads it via the button (not only visits the public sharing page), the notification from my screenshot is created.
