### ISSUE TITLE
Undefined steps causing tests fail

### ISSUE THREAD

**Issue by SagarGi** [owncloud/activity#1110]
Builds: 
https://drone.owncloud.com/owncloud/activity/2752/21/17
```
console
/**
     * @When the public downloads file :arg1 from inside the last public shared folder with range :arg2 using the old public WebDAV API
     */
    public function thePublicDownloadsFileFromInsideTheLastPublicSharedFolderWithRangeUsingTheOldPublicWebdavApi($arg1, $arg2)
    {
        throw new PendingException();
    }
```
https://drone.owncloud.com/owncloud/activity/2752/22/17

--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @When the public downloads file :arg1 from inside the last public shared folder with range :arg2 using the old public WebDAV API
     */
    public function thePublicDownloadsFileFromInsideTheLastPublicSharedFolderWithRangeUsingTheOldPublicWebdavApi($arg1, $arg2)
    {
        throw new PendingException();
    }

https://drone.owncloud.com/owncloud/activity/2752/23/10

--- FeatureContext has missing steps. Define them with these snippets:

    /**
     * @When the public renames file :arg1 to :arg2 from the last public share using the new public WebDAV API
     */
    public function thePublicRenamesFileToFromTheLastPublicShareUsingTheNewPublicWebdavApi($arg1, $arg2)
    {
        throw new PendingException();
    }

 
The above undefined steps are causing fail in this app. All the undefined steps are related to the public link share. This might be related to this PR https://github.com/owncloud/core/pull/40114.

**Comment by phil-davis** [comment]
Yes, in feature files, wherever the step says something like `last public` you will need to change it to `last public link`

I made the words more consistent for all steps in core.
