### ISSUE TITLE
Bring time from the mail with config option back

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/activity#1135]
### Steps to reproduce
1. Update activity to 2.7.1
2. Get Activity E-Mail without the time

### Expected behaviour
Tell us what should happen

Config option to display the time in the e-mail. By default, only the day is displayed.
Are there any legal regulations that prevent the display of the time?

### Actual behaviour
Tell us what happens instead

**Comment by phil-davis** [comment]
Share expiry always happens effectively at the end of the expiry date. But the processing of that expiry happens whenever the share is next attempted to be accessed, or when the cron job runs. For share expiry the activity time was misleading.

But it seems that the time was removed in all cases. IMO the code should be made smarter, and the time be put back for all activity notifications except share expiry.

Related issue #1131 

@pmaier1 FYI

**Comment by prsnbrg** [comment]
Sorry for the duplicate.
I will close here and all related comments should be made in #1131
