### ISSUE TITLE
Various tests are failing in nightly 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/activity#1143]
Link to builds:
https://drone.owncloud.com/owncloud/activity/2977
https://drone.owncloud.com/owncloud/activity/2976
https://drone.owncloud.com/owncloud/activity/2975

The following tests are failing in nightly:
```
webUIActivityComments/comments.feature:67
webUIActivityComments/comments.feature:68
webUIActivityComments/comments.feature:115
webUIActivityComments/comments.feature:116
webUIActivityComments/comments.feature:118
webUIActivityTags/tags.feature:45
webUIActivityTags/tags.feature:46
webUIActivityTags/tags.feature:91
webUIActivityTags/tags.feature:92
webUIActivityTags/tags.feature:94
apiActivity/list.feature:1105
```
The tests are failing mainly in the then step 

```
 Then the activity number 1 should contain message "Carol King commented on simple-empty-folder" in the activity page                    # WebUIActivityContext::theActivityNumberShouldContainMessageInTheActivityPage()
      Failed asserting that 'You shared simple-empty-folder with CCarol King' contains "Carol King commented on simple-empty-folder".
```

Might be due to some changes in core or might be a bug

**Comment by grgprarup** [comment]
The failures are hard failures against the recent core. The findings using git bisect tests are failing after PR

**Comment by grgprarup** [comment]
The failures are hard failures against the recent core. The findings using git bisect tests are failing after PR

**Comment by grgprarup** [comment]
The failures are hard failures against the recent core. I tried git bisect to find the bad commit.
The tests are failing after PR https://github.com/owncloud/core/pull/40421 is merged
No activities are reported on sharee activity page even though the shares are accepted.
CC @DeepDiver1975 @phil-davis @individual-it

**Comment by DeepDiver1975** [comment]
> apiActivity/list.feature:1105

In the second expectation the path seems to be different.
As per feature ```FolderForBrian/textfile0.txt``` but during my local test I did receive only ```textfile0.txt```

The same applies to the 3rd expectation

**Comment by DeepDiver1975** [comment]
Looking into the logic in https://github.com/owncloud/activity/commit/c2283d12bfcd29b0f3d101c9fec273954c521661#diff-51badeda9d579fdcc8e3b251d317c754e984139406d3f73e1569daf50049774dR199

It is correct to not display folder and filename - but only file name.

:confused:

**Comment by DeepDiver1975** [comment]
> The tests are failing after PR [owncloud/core#40421](https://github.com/owncloud/core/pull/40421) is merged

Same behavior on a commit before this change

**Comment by grgprarup** [comment]
@DeepDiver1975 The `webui` tests for comments and tags are failing for group share only. When a file or folder is shared with `group` then no activities are reported for `sharee` even if the share is accepted but working fine for user share.

**Comment by DeepDiver1975** [comment]
I will look into these scenarios as well.  But the failing API test is a false negative to me.

**Comment by grgprarup** [comment]
Changes that cause fail the CI are reverted with PR https://github.com/owncloud/core/pull/40454. So closing this issue.

**Comment by DeepDiver1975** [comment]
I am about to bring back the original change - https://github.com/owncloud/core/pull/41078

Can I ask you to setup ci on a pr in here to see if the problem still exists? THX

@grgprarup @SwikritiT

**Comment by grgprarup** [comment]
> I am about to bring back the original change - [owncloud/core#41078](https://github.com/owncloud/core/pull/41078)
> 
> Can I ask you to setup ci on a pr in here to see if the problem still exists? THX
> 
> @grgprarup @SwikritiT

Sure. I will make one.

**Comment by grgprarup** [comment]
> I am about to bring back the original change - [owncloud/core#41078](https://github.com/owncloud/core/pull/41078)
> 
> Can I ask you to setup ci on a pr in here to see if the problem still exists? THX
> 
> @grgprarup @SwikritiT

I have made the PR https://github.com/owncloud/activity/pull/1197 , but the tests are failing. 
Build: https://drone.owncloud.com/owncloud/activity/3630/20/12

**Comment by SwikritiT** [comment]
Can this issue be closed now @grgprarup @DeepDiver1975 ?

**Comment by phil-davis** [comment]
The new core PR https://github.com/owncloud/core/pull/41078 was merged. Nightly CI is still passing, so that core PR did not accidentally break the behavior in the activity app - good.

Closing this issue.
