### ISSUE TITLE
Daily tarballs are not updated

### ISSUE THREAD

**Issue by saw-jan** [owncloud/activity#1167]
Caught on nightly: https://drone.owncloud.com/owncloud/activity/3274/1/2

```bash
-----------------------------------------------------------------
[INFO] Checking tarball 'owncloud-daily-master.tar.bz2'
[INFO] Downloading 'https://download.owncloud.com/server/daily/owncloud-daily-master.tar.bz2'
[INFO] Extracting tarball to '/tmp/owncloud'
[ERROR] Daily tarball 'owncloud-daily-master.tar.bz2' is not up to date
[INFO] Tarball build date: 2023-03-26
[INFO] Today: 2023-03-28

-----------------------------------------------------------------
[INFO] Checking tarball 'owncloud-daily-master-qa.tar.bz2'
[INFO] Downloading 'https://download.owncloud.com/server/daily/owncloud-daily-master-qa.tar.bz2'
[INFO] Extracting tarball to '/tmp/owncloud'
[ERROR] Daily tarball 'owncloud-daily-master-qa.tar.bz2' is not up to date
[INFO] Tarball build date: 2023-03-26
[INFO] Today: 2023-03-28
```

Link: https://download.owncloud.com/server/daily/
![Screenshot from 2023-03-28 09-54-27](https://user-images.githubusercontent.com/52366632/228125850-945ef620-f166-4369-9a3b-eb33168d3c7f.png)

**Comment by saw-jan** [comment]
CC @phil-davis

**Comment by phil-davis** [comment]
@jnweiger "something happened" (TM) and the daily tarball did not get updated last night.

`version.php` in the current tarball has:
```
$OC_Build = '2023-03-26T22:04:17+00:00 794521f358fac84dd9a4b7dca0a7ec4b11404596';
```
So it is 1 day out-of-date.

**Comment by saw-jan** [comment]
Daily builds reappeared. https://drone.owncloud.com/owncloud/activity/3276/1/2
Closing this here.

**Comment by saw-jan** [comment]
Again no new daily builds from Mar 30 and 31
CC @jnweiger

**Comment by saw-jan** [comment]
No daily tarball builds
https://drone.owncloud.com/owncloud/activity/3387/1/2
https://download.owncloud.com/server/daily/?sort=time&order=asc

**Comment by phil-davis** [comment]
```
-----------------------------------------------------------------
[INFO] Checking tarball 'owncloud-daily-master.tar.bz2'
[INFO] Downloading 'https://download.owncloud.com/server/daily/owncloud-daily-master.tar.bz2'
[INFO] Extracting tarball to '/tmp/owncloud'
[ERROR] Daily tarball 'owncloud-daily-master.tar.bz2' is not up to date
[INFO] Tarball build date: 2023-06-01
[INFO] Today: 2023-06-05
-----------------------------------------------------------------
[INFO] Checking tarball 'owncloud-daily-master-qa.tar.bz2'
[INFO] Downloading 'https://download.owncloud.com/server/daily/owncloud-daily-master-qa.tar.bz2'
[INFO] Extracting tarball to '/tmp/owncloud'
[ERROR] Daily tarball 'owncloud-daily-master-qa.tar.bz2' is not up to date
[INFO] Tarball build date: 2023-06-01
[INFO] Today: 2023-06-05
```

@jnweiger the daily-master-qa tarball has `version.php` with:
```
$OC_Build = '2023-06-01T22:00:27+00:00 7860860c97efed34bb01e038765c9e49cc86be05';
```
Something has happened to the nightly core tarball build.

**Comment by jnweiger** [comment]
I've added a workaround to the makedailysnapshots.sh script. We now try harder to remove artefacts older than one month.
Please ping again, if nothing appears tomorrow morning.

**Comment by phil-davis** [comment]
tarball was generated successfully last night.

**Comment by saw-jan** [comment]
Daily builds not updated: https://download.owncloud.com/server/daily/?sort=time&order=desc

**Comment by phil-davis** [comment]
See discussion in https://chat.owncloud.com/channel/btr?msg=BqXkqW5oJkMrr6Xvc

Needs php-apcu extension installed on the system that creates the daily tarballs.
@jnweiger is aware.

**Comment by saw-jan** [comment]
Again, it's not updated: https://drone.owncloud.com/owncloud/activity/3613/1/2

**Comment by phil-davis** [comment]
Tarball was updated last night: https://drone.owncloud.com/owncloud/activity/3621/1/2

The fix was PR https://github.com/owncloud/market/pull/1302
