### ISSUE TITLE
Release activity 2.7.2

### ISSUE THREAD

**Issue by phil-davis** [owncloud/activity#1176]
### Reasons

- Needed to go with server core 10.13 because of the Symfony 4 to 5 upgrade https://github.com/owncloud/core/issues/39630
- PR #1173 made code changes needed for Symfony 5
- #1181 (not yet merged)??

Note: the change in that PR also works fine with server core 10.12 and before, so there should be no need to bump the core min-version.

The app can be released any time before 10.13 - it should work fine with any of the recent oC10 core releases.

## Needs full QA
- Testplan #1184

**Comment by jnweiger** [comment]
Release done together with 10.13.0
