### ISSUE TITLE
[QA] activity mail notofication for shared folder has wrong timestamp

### ISSUE THREAD

**Issue by jnweiger** [owncloud/activity#1191]
Seen with activity 2.7.2 and core 10.13.0-beta.1

* User Alice renames their photos folder to alicepics
* User Alice shares this folder with user admin.
* User Alice shares this folder with group admin.

This activity mail is sent:
```
  "Date": "Wed, 16 Aug 2023 12:19:23 +0000",
  "To": "admin <admin@jw-qa.owncloud.works>",
  "Subj": "Benachrichtigung =?utf-8?Q?über?= die =?utf-8?Q?Aktivitäten?=",
  "Body": "
--_=_swift_1692188363_794f2464e4895f487e2f641f1cfde88e_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hallo admin,

Du erhältst diese E-Mail, weil folgendes auf https://oc10130b1-wnd-20230815.jw-qa.owncloud.works/ geschehen ist

* Alice hat alicepics mit Dir geteilt - 1. Januar 1970
* Alice hat alicepics mit Dir geteilt - 1. Januar 1970

--
ownCloud - Store. Share. Work.
https://owncloud.com

--_=_swift_1692188363_794f2464e4895f487e2f641f1cfde88e_=_
```

**Comment by hodyroff** [comment]
Is the stream wrong as well, or just the email?

**Comment by IljaN** [comment]
Can't reproduce on core and activity master .

Normal share:

![image](https://github.com/owncloud/activity/assets/246983/3f205c98-cc19-41ce-8e60-4b9c8ba9bc4d)

Manually backdating:
![image](https://github.com/owncloud/activity/assets/246983/1cd8e87b-0db1-4089-9736-d77fb575a5f9)

**Comment by IljaN** [comment]
Using german template:

![image](https://github.com/owncloud/activity/assets/246983/23a0a4ea-cae7-43ce-a346-7cec664a5ee0)

**Comment by IljaN** [comment]
2.7.2 Tag specifically:

![image](https://github.com/owncloud/activity/assets/246983/027dcfb9-a8ec-4666-a563-4de16b5e9f29)

![image](https://github.com/owncloud/activity/assets/246983/0c18ca01-76a2-4937-8fb3-b69009602935)

**Comment by IljaN** [comment]
@jnweiger Do you have more hints? Could you maybe please provide the related db-entries from oc_activity and oc_activity_mq and the notification settings from the WebUI?

**Comment by jnweiger** [comment]
I can no longer reproduce the issue, not even on the very same machine with the very same users. :man_shrugging:
