### ISSUE TITLE
Notification mails sometimes use a wrong language

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/activity#145]
The title is translated correctly, but the email text sometimes is in the language of the user which triggered the email, rather then the recipient.

Copied from owncloud/core#10859

**Comment by kalletabur** [comment]
These notifications are sent when I share file/folder and fill checkbox "notify by mail".
These notification are in language I (meaning sharer) have set up for myself over web interface.
We are using ownCloud 7.0.4.

**Comment by nickvergessen** [comment]
That is not the activity app, but the files_sharing app in core

**Comment by enoch85** [comment]
@nickvergessen I still have the same issue on oC 8.

![screenshot_2015-02-24-14-56-05](https://cloud.githubusercontent.com/assets/4511254/6379878/c2f00fdc-bd35-11e4-8d6e-2d00d5c1ae34.png)

**Comment by nickvergessen** [comment]
??

**Comment by enoch85** [comment]
@nickvergessen Yes, same issue as https://github.com/owncloud/core/issues/10859

The issue persists in ownCloud 8.

**Comment by nickvergessen** [comment]
Jup, found the issue :see_no_evil:

**Comment by nickvergessen** [comment]
Fixed in 8.1
Im not sure whether we can get the BC break backported, but maybe you can ask for it, or fix it locally on your end

**Comment by enoch85** [comment]
Thanks!

**Comment by kalletabur** [comment]
Tested this again on "ownCloud 8.0.2 (stable)" and still these emails are displayed in the language of the user, who triggered the email, rather then the recipient.
Recipient uses english, sharer used 3 different languages and recipient got all these notifications in different language.

**Comment by nickvergessen** [comment]
@kalletabur well it will be fixed in 8.1:
> Fixed in 8.1
Im not sure whether we can get the BC break backported, but maybe you can ask for it, or fix it locally on your end

**Comment by kalletabur** [comment]
> @kalletabur well it will be fixed in 8.1
Sorry, I thought that by 8.1 was meant 8.0.1. In oC 7 version numbering was 7.0.something.

**Comment by nickvergessen** [comment]
8.1 is 8.1.0 :wink: sorry ;)

**Comment by kalletabur** [comment]
np :)

**Comment by kalletabur** [comment]
Now we have upgraded our servers to 8.1.1 and still users to whom files/folders are shared get notifications based what language sharer uses.
Seems to me that this is still not resolved.
I used test folder/file to test this. Before sharing I changed language (Estonia -> Finnish -> Russian) and as you can see user (language is set English) gets notifications in wrong language
![share-notifications-not-in-my-language](https://cloud.githubusercontent.com/assets/8167593/9307737/d1a98958-4508-11e5-818e-df2e11683361.png)

**Comment by enoch85** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Yeah, just fixed the issue last week. It's an issue in core's file app, which ignores the language key the activitiy app provides to it:
https://github.com/owncloud/core/pull/18171

Will be fixed in 8.1.2 and 8.2

**Comment by kalletabur** [comment]
Tested it with 8.1.3 and notifications still are using wrong language - it is using the language of the sharer not the language of the user who recieves the notification.
I shared 3 files with email notifications. 1st time my personal language was finnish, 2nd time english and 3rd time estonian. The user who recieved notifications has language set to english. He recieved these notification with 3 different languages (finnish, english and estonian).

**Comment by nickvergessen** [comment]
It will be in 8.1.4, see https://github.com/owncloud/activity/issues/373

**Comment by nickvergessen** [comment]
If you can't wait feel free to patch your instance with https://github.com/owncloud/core/pull/18572

**Comment by kalletabur** [comment]
applied patch 18572 on dev server, confirmed that changes were applied, tested and still notifications are different languages. 
ownCloud version 8.1.3, Debian 8.2, PHP 5.6.13, MySQL 5.5.44, NGINX 1.6.2-5

**Comment by nickvergessen** [comment]
Well it needs a login from the affected users before the email is sent.
Also make sure that when you login the language is what you expect

**Comment by kalletabur** [comment]
How I tested:
Created test user (lets call it user1), let another user (lets call it user2) log in to web (on this patched dev server) and let him change personal language to estonian.
3 files were created previously.
after that I log in over web using user1.
user1 changed personal language to English and shared 1st file to user2 (with mail notification) -> user2 recieved mail in English
user1 changed personal language to Russian and shared 2nd file to user2 (with mail notification) -> user2 recieved mail in Russian
user1 changed personal language to Finnish and shared 3rd file to user2 (with mail notification) -> user2 recieved mail in Finnish

If you know more ways to change test details, please let me know.

**Comment by nickvergessen** [comment]
Works for me:

> Tere test1,
> 
> Sa sead selle teavituse, kuna viimase tunni jooksul toimusid http://localhost/ownCloud/eightOne/core/ sellised tegevused
> 
> * admin jagas sinuga welcome (2).txt

**Comment by kalletabur** [comment]
Seems that we are talking about different notifications.
What I mean is that if I share something to someone and click check button send notification with mail then someone should get notification in language what he have choosen not what I have choosen.
The notification you shared (in lovely estonia :D ) is activity notification.

**Comment by nickvergessen** [comment]
> What I mean is that if I share something to someone and click check button send notification with mail

That is not from the activity app, but I see the issue now. Please create a new issue in core
