### ISSUE TITLE
Show the email address, you shared a link with

### ISSUE THREAD

**Issue by trigonova** [owncloud/activity#168]
Hey,
when i share a link and send it to a mail address, i don't see in my activity with who i shared this link.
![activity](https://cloud.githubusercontent.com/assets/7849016/4882658/0fa60ee4-6359-11e4-83fe-b3e77e0b8e56.jpg)
Can you may implement this or is there already a way to customize this?

- [ ] Depends on owncloud/core#11951

**Comment by nickvergessen** [comment]
Closing in favor of owncloud/core#11951
This should not be done in the activity app, but the sharing app.
