### ISSUE TITLE
Activity notification does not list activities by unknown users over shared links

### ISSUE THREAD

**Issue by JensKirchner** [owncloud/activity#177]
Activities on public shared folders by unknown users (shared via link) are not listed in the activity log (or mail notification about activities). However, it would be very useful to have such activities logged as well. Since these users are unknown, information about the IP addresses would be useful.

**Comment by MorrisJobke** [comment]
@nickvergessen Was also requested in core by @gig13 owncloud/core#17573

**Comment by nickvergessen** [comment]
Yeah, will have a look again, but iirc that is a core issue in the end. Let me check

**Comment by gig13** [comment]
@cmonteroluque @bboule 
From my perspective this is not an enhancement, but a bug. Is there any ETA on availability?

**Comment by nickvergessen** [comment]
I seem to have fixed this somewhere in the meantime (before 8.1). At least creating and changing trigger activities as expected:
* "remote user" changed powertop.sh
* "remote user" created powertop.sh

Also works for emails.

So, closing

**Comment by gig13** [comment]
@nickvergessen @cmonteroluque @bboule 
Which version was it fixed in?

**Comment by nickvergessen** [comment]
Just tested it on stable8 and it even works there, but stable7 seems not to.

So fixed in 8.0

**Comment by cmonteroluque** [comment]
thank you Joas

**Comment by gig13** [comment]
@MorrisJobke @nickvergessen 
Where is the backport code for testing?

**Comment by MorrisJobke** [comment]
> Where is the backport code for testing?

There was nothing backported. It was just tested if it work in older versions. It seem that it worked in stable8 but not in stable7.

**Comment by MorrisJobke** [comment]
I tested it again on stable8 (upcoming 8.0.6) and it works:

![bildschirmfoto von 2015-07-21 15-50-59](https://cloud.githubusercontent.com/assets/245432/8802236/7203af22-2fc0-11e5-9015-f358cad19d2a.png)
