### ISSUE TITLE
[Feature request] Delete old activities

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/activity#208]
Hi,
as far as i know currently there is no way of deleting older activities as a user or an admin.
For bigger oC instances the oc_activity table can get big and will keep getting bigger. After upgrade to oC 7 i noticed oc_activity has grown considerably big and bigger than oc_filecache.
We could for instance delete all the user activities older than, say, 3 months.
Would be very useful instead having to truncate the whole table and loose all user activities.
Thanks.

**Comment by nickvergessen** [comment]
https://github.com/owncloud/activity/blob/master/lib/backgroundjob/expireactivities.php#L38-L39
