### ISSUE TITLE
notify when uploading a file to a shared folder via url

### ISSUE THREAD

**Issue by codesse** [owncloud/activity#217]
Hello,

notify (and activity) works fine when a user uploads/deletes a file to/from her folder, but doesn't do anything if someone who received an url for that folder with upload permissions uploads a file.
I've checked oc_activity and oc_activity_mq to see if something logs there when the latter occurs but it doesn't.

os : Debian 6.0.8
lamp : apache 2.2.16/php5.4.24/mysql5.5.31
oc : 7.0.4

Thanks,

**Comment by karlitschek** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
Duplicates #177
