### ISSUE TITLE
255 characters is too short for subject and message parameters

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/activity#254]
Most activities contain a uid + filepath as subject parameters.
The uid is 64 characters as per `oc_users`.`uid`
File path is `oc_filecache`.`name` (250) + `oc_filecache`.`path` (4000), so 4250 characters in worst case.

However the planned move/rename activity might have 2 file paths in max length, so I think we should change the column from VAR(255) to TEXT, to avoid problems with apps.

The existing broken entries should be deleted on update:
```sql
SELECT *
FROM `oc_activity`
WHERE `subjectparams` NOT LIKE '%}' OR `messageparams` NOT LIKE '%}'
```

Error log from broken entries:
```
unserialize(): Error at offset 248 of 256 bytes at /var/www/apps/activity/lib/grouphelper.php#69

**Comment by y-a-v-a** [comment]
+1
I noticed this when migrating from sqlite to pgsql. I had to drop my database, modify the database.xml schema by hand (enlarged some values to 2048) and reran the db migration script. My impression is that it works nicely now.
