### ISSUE TITLE
crash error loading when disabling image avatars of users

### ISSUE THREAD

**Issue by mckaygerhard** [owncloud/activity#256]
if setup in config "enable_avatars" to false, the activity app could not load due following javascrip error:

```
Uncaught TypeError: Object [object Object] has no method 'avatar' script.js:117
(anonymous function) script.js:117
x.extend.each jquery-1.10.0.min.js:4
x.fn.x.each jquery-1.10.0.min.js:4
OCActivity.InfinitScrolling.processElements script.js:115
OCActivity.InfinitScrolling.appendContent script.js:110
(anonymous function) script.js:47
c jquery-1.10.0.min.js:4
p.fireWith jquery-1.10.0.min.js:4
k jquery-1.10.0.min.js:6
r jquery-1.10.0.min.js:6
```

so then the option must parse and revised to oc v 6 , oc v 7 and oc v 8, the script assumed that the avatar element are always present!!! and this are configurable!

must put a conditional here!

**Comment by mckaygerhard** [comment]
confirmed that this still happened in oc 8 and also lasted oc 7, causes activity app crash when disabling avatars to false.

solved if put firts 
if ( typeof element.avatar == 'function' )

before 	https://github.com/owncloud/activity/blob/master/js/script.js#L115

**Comment by nickvergessen** [comment]
Oh, I didn't know it can be disabled. Thanks for reporting

**Comment by nickvergessen** [comment]
8.1: #257
8.0: #258 
7.0: #259

**Comment by mckaygerhard** [comment]
error.. well, i think of with a simple typeof to the object for verify if function exists could fix but this commit are very large.. if someone reports that works well close the issue, i cant verify that due i not update the oc deploy, when changes are too many rather that few lines, and redeploy again a test environment with all my changes are very tired

**Comment by nickvergessen** [comment]
Well yes, that "would" have worked aswell. But I fixed the reason, rather then the symptom.
Instead of create the avatar placeholder and then not processing js on it, I just dont add the placeholder, so we dont need to process anything at all.

**Comment by mckaygerhard** [comment]
that's right! close it!

**Comment by nickvergessen** [comment]
reopening until the PRs are merged ;)
