### ISSUE TITLE
When multiple files/folders are grouped into one message, show multiple icons/thumbnails

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#272]
Currently every action just has one icon or thumbnail. That way it always looks as if you just modified one thing.

Instead, when there were for example 7 images uploaded, it should show the thumbnails of those images. For the text above we have a limit of 5, after that it shows `and x more …`, so we can also cut off after the first 5 thumbnails and show a dot-dot-dot next to that.

cc @nickvergessen

**Comment by jancborchardt** [comment]
This results in having multiple screenshot for only one file:
![capture du 2015-08-14 14-33-42](https://cloud.githubusercontent.com/assets/925062/9273953/813719dc-4291-11e5-8d88-ab0967769f25.png)
Only a screenshot of the latest version should be shown @nickvergessen :)

**Comment by nickvergessen** [comment]
noticed the same just now, thanks
