### ISSUE TITLE
Customise RSS and JSON output

### ISSUE THREAD

**Issue by jiujiu** [owncloud/activity#278]
Dear all,

First of all the code we use in stable on branch stable7.

Then I would like to know what is the best practices / hints to customise the file rss.php in order to accept parameter filter=self and a specific number of results.

Finally I wonder if we need something specific in order to create the same result in JSON?

Sincerely yours,

Julien

**Comment by karlitschek** [comment]
Thanks for your question. This is the owncloud bugtracker. Because this is not a bug I suggest that you ask the question in the owncloud forum or on the mailinglist. Thanks.
