### ISSUE TITLE
File and folder location is wrong at shared external folders

### ISSUE THREAD

**Issue by tibmanus** [owncloud/activity#284]
### Steps to reproduce
1. Admin user mounts a local folder as an external storage. (Folder name: Localhhh)
2. Admin user creates a folder inside this folder (Folder name: external), then shares it with 'testuser'.
3. Testuser creates a file in this folder (Name: file1).
4. Testuser checks the Activity app: "You created file1"

### Expected behaviour
Tooltip and link shows the correct location for testuser: external/

### Actual behaviour
Tooltip and link for testuser goes to this location:   externalcalhhh/external

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache2

**Database:**
SQLite

**ownCloud version:** (see ownCloud admin page)
8.02

**Updated from an older ownCloud or fresh install:**
Happens both at fresh and updated version.

**Are you using external storage, if yes which one:**
local

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no

**Comment by karlitschek** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
Can't reproduce with SFTP mount, and local is not working here atm.
Can you test whether it affects SFTP mounts at your site aswell?

**Comment by tibmanus** [comment]
Can't test SFTP, sorry.

**Comment by nickvergessen** [comment]
Okay, confirmed, it's an issue in core thou. Will reopen the ticket there

**Comment by nickvergessen** [comment]
Replaced by https://github.com/owncloud/core/issues/15858
