### ISSUE TITLE
Searching in activity view shows second "No results"

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/activity#287]
![2015-04-28_13-49-02](https://cloud.githubusercontent.com/assets/878997/7368941/809f5d4c-edad-11e4-9d43-4706598af1af.png)

@nickvergessen Any idea how to fix this? – This is on one of the latest EE 8.0.3 build

**Comment by LukasReschke** [comment]
Or is this expected? – Looks a little bit off though.

cc @jancborchardt

**Comment by nickvergessen** [comment]
problem with the core
