### ISSUE TITLE
Exclude your own actions in the RSS activity feed

### ISSUE THREAD

**Issue by axllent** [owncloud/activity#289]
It does not seem possible to filter **out** (exclude) your own activities in the RSS activity feed. I would assume that by unticking "List your own actions in the stream" one would get only other's activities, yet this seems to have no effect (I still see "You created...", "You deleted...", "You changed....."). I've just upgraded to 8.0.3 but still no difference.

What I am trying to achieve is getting an RSS feed (or email notification) of only other users / anonymous uploads / downloads etc, and entirely ignore my own actions. 

![screenshot-2015-05-05 21-28-49](https://cloud.githubusercontent.com/assets/1463435/7470105/49072de4-f36e-11e4-9ef8-74d1560ea92d.png)

**Comment by nickvergessen** [comment]
`List your own actions in the stream` works for me.
Which ownCloud and Activity version are you using?

**Comment by axllent** [comment]
Currently using Activity v1.2.0. I've had this issue since I installed owncloud (early 7 release). Initially I just kept getting emails of my own actions so I stopped using it, figuring it was a bug, but it's still does the same now, so... :-) 

Please let me know if you need any more info. I'm an administrator on the server (it is a small production server though).

**Comment by nickvergessen** [comment]
Well then this got fixed in the mean time. You may try to update to ownCloud 8 with a newer version of the activity app.
If the issue then still exists for you, feel free to reopen the issue.

**Comment by axllent** [comment]
Sorry for the misunderstanding. As per my initial post, this is on ownCloud 8.0.3, but this issue has existed since early 7 releases.

**Comment by nickvergessen** [comment]
Right, I just realised that we didn't backport two lines, sorry will be fixed in 8.0.4 then

**Comment by axllent** [comment]
Super, thanks! So I take it this is a known issue then, and not that my installation is borked or something?

**Comment by nickvergessen** [comment]
Yeah, you can apply https://github.com/owncloud/activity/pull/291/files to fix the issue on your installation, until the next release is out

**Comment by axllent** [comment]
Awesome, I can confirm the patch fixes it! Thanks for the update.

**Comment by axllent** [comment]
For what it's worth (although it may have a separate patch), email notifications still report one's own actions despite `Notify about your own actions via email` being unticked :) RSS works as expected though with the patch. Hope this helps!

**Comment by nickvergessen** [comment]
Sorry to say, but the email settings do not work retro-active atm.
So when the notification was triggered before you changed the setting, you will still get the email notification for it.

**Comment by axllent** [comment]
Unfortunately that doesn't seem to be the case here - I continued to get several email notifications today with my own actions **after** ticking and then unticking `Notify about your own actions via email ` (to make sure the setting was unset this morning). Anyway, RSS works as expected :)

**Comment by nickvergessen** [comment]
@axllent feel free to try https://github.com/owncloud/activity/issues/297

**Comment by axllent** [comment]
Excellent, the patch seems to fix it (I'm not receiving notifications of my own actions via email, yay)! Good work, thanks for the follow-up.
