### ISSUE TITLE
Seperate file and folder in activity notifications

### ISSUE THREAD

**Issue by enoch85** [owncloud/activity#292]
### Steps to reproduce
1. Share a folder with files in it.
2. Download a file in that folder.

### Expected behavior
It should be the file that shows as downloaded.

### Actual behavior
The folder shows as downloaded.

### Server
8.0.3

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/pull/15502 8.0.4 / 8.1

**Comment by enoch85** [comment]
@nickvergessen So you mean that you already fixed this in a PR that's older than this issue?

**Comment by nickvergessen** [comment]
Yes, but the PR was merged after the release of 8.0.3

**Comment by enoch85** [comment]
@nickvergessen So in other words - this should work already? Well, it doesn't.

**Comment by nickvergessen** [comment]
No, it works on master and stable8, but not in 8.0.3, because the fix was merged after the release of 8.0.3
