### ISSUE TITLE
Activity for federated sharing

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/activity#299]
I thought I entered this someplace or that I saw this someplace but I can't seem to locate it.

### Steps to reproduce

1. Install 8.1 on two systems
2. from system 1, share a file with a user on system 2

### Expected behaviour

Should see the share on the activity stream

### Actual behaviour

Do not see the share on the activity stream

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-12T03:08:46+00:00 20d2d8d3ddee2750343bdec69a3e7031b710039a

### Client configuration:

owncloudcmd veresion 1.8.1

**Comment by karlitschek** [comment]
@schiesbn

**Comment by nickvergessen** [comment]
Seems like it currently only adds an activity when the share is accepted or received:
![remote-sharing](https://cloud.githubusercontent.com/assets/213943/7604864/29d5b4f0-f949-11e4-8aac-47864c23d105.png)

Will do a follow up to add the "You shared ..." notification aswell

**Comment by jancborchardt** [comment]
I have a similar issue where the activity does not show the name of the person, only `remote user`:
![activity remote user](https://cloud.githubusercontent.com/assets/925062/8104649/b69aed2e-1032-11e5-9925-68a9b2e95b5a.png)
cc @nickvergessen @schiesbn

**Comment by nickvergessen** [comment]
@jancborchardt that is a problem with core, we have an empty name in the session for "guest" users, nothing we can do about it.

**Comment by jancborchardt** [comment]
Well we could say `A guest` in that case :)

**Comment by nickvergessen** [comment]
Well there are no such things as "guests", so I abstained from introducing a new word for them and used what is already known.
We could easily change the word in https://github.com/owncloud/activity/blob/master/lib/parameterhelper.php#L169-L171, but I'd like to not break translations so close to a release.

**Comment by jancborchardt** [comment]
Ok, ok. In the future though keep in mind to let me know about stuff like that. And in no case do we use " quote marks anywhere – just write the name out.

**Comment by nickvergessen** [comment]
Duplication of #350
