### ISSUE TITLE
Add IP adress as information on downloaded folders and files 

### ISSUE THREAD

**Issue by enoch85** [owncloud/activity#301]
If it's possible it would be very cool if you could see the IP adress of the ones who download a shared link in the activity feed. Maybe like a tooltip or something.

What do you think @nickvergessen is that possible?

**Comment by nickvergessen** [comment]
Duplicates/related to https://github.com/owncloud/activity/issues/177

**Comment by enoch85** [comment]
Keeping the discussion there then.
