### ISSUE TITLE
Settings improvements

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#302]
@nickvergessen how about this?
![capture du 2015-05-22 10 31 47](https://cloud.githubusercontent.com/assets/925062/7766861/d6e7ed40-006d-11e5-8fe3-92e028304ead.png)
* [ ] Disable »Mail« checkbox in activity settings for limiting to favorites, since it’s only available in stream.
* [ ] Put »Include your own activities« in the proper list with checkbox for both mail & stream, only stream being default

cc @owncloud/designers

**Comment by nickvergessen** [comment]
>  Disable »Mail« checkbox in activity settings for limiting to favorites, since it’s only available in stream.

Good idea, will be a bit hacky, but doable

**Comment by jancborchardt** [comment]
Cool, thanks!
