### ISSUE TITLE
The oc_activity table is not cleaned as defined in config.php, after 14 days in my case

### ISSUE THREAD

**Issue by enricocanino** [owncloud/activity#309]
Hi all, I have the following configuration:
-owncloud server 8.0.3.4
-dbtype mysql
-activity_expire_days 14
-webcron that works fine every 15 minutes
-about 60 users
-about 1'100'000 files in data directory in total 70 GB
-about 1 GB of mysql

The problem is that oc_activity table is not cleaned as defined in config.php, after 14 days.

The value activity_expire_days, at the installation time, was default, yesterday I modified that parameter, in config.php, and nothing success.

I wait one day and nothing success: mysql oc_activity table contains a lot of entry since first installation date.

It is a bug?

TIA

**Comment by nickvergessen** [comment]
Please run the following queries on your database, to help find out if that is the issue:
```sql
SELECT * FROM `oc_jobs` WHERE `class` LIKE '%Expire%'
```
and
```sql
SELECT COUNT(*) AS num_jobs FROM `oc_jobs` WHERE `last_run` = 0
```

**Comment by enricocanino** [comment]
oc_jobs contains only 3 record as you can see in screenshot.jpg
![screenshot](https://cloud.githubusercontent.com/assets/12700982/8326905/b6cfe204-1a64-11e5-9b71-d89a665c18e8.jpg)

**Comment by nickvergessen** [comment]
Okay, looks like the job was executed the last time "Tuesday, 23-Jun-15 12:21:03 UTC"

If that was before you changed the setting, it should be run in ~2 hours again (its only run all 24hours). If that does not help, then please post your config.php (with removed passwords, salts and domains) here, like mentioned in the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by enricocanino** [comment]
### Steps to reproduce
1. Have a lot of records in oc_activity
2. Modify activity_expire_days from default to 14 (days) in config.php

### Expected behaviour
oc_activity table must decrease number of records after 24 hours
oc_jobs havew this entry: OCA\Activity\BackgroundJob\ExpireActivities 1435062063 and apperas to be older than 24 hours

### Actual behaviour
oc_activity table does not decrease his number of records

### Server configuration
Linux (Linux opus51 3.12.25-opus #1 SMP Thu Jul 31 13:37:45 CEST 2014 x86_64)
Apache 2.4
MySQL5.5.34-enterprise-commercial-advanced-log
Php 5.4.4-14+deb7u2
8.0.3.4
Fresh install

**List of activated apps:**

Activity 1.2.0
Calendar
Contacts
Deleted files
Documents
External Sites
File Locking 
First Run Wizard
Mail Template Editor
PDF Viewer
Pictures
Provisioning API
RainLoop
Share Files
Text Editor
Versions
Video VIewer

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'blabla',
  'passwordsalt' => 'blabla',
  'secret' => 'blabla',
  'trusted_domains' => 
  array (
    0 => 'blabla',
    1 => 'blabla',
  ),
  'datadirectory' => '/htdocs/public/www/cloud/data',
  'overwrite.cli.url' => 'blabla',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'blabla',
  'dbhost' => 'blabla',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'blabla',
  'dbpassword' => 'blabla',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'blabla',
  'forceSSLforSubdomains' => true,
  'overwritewebroot' => '',
  'loglevel' => 2,
  'theme' => 'blabla',
  'skeletondirectory' => 'blabla',
  'remember_login_cookie_lifetime' => 604800,
  'activity_expire_days' => 14,
  'trashbin_retention_obligation' => 15,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
Indifferent  for this issue

**Operating system:**
Indifferent
### Logs
#### Web server error log
No errors  for this issue
Insert your webserver log here
No errors log  for this issue

#### ownCloud log (data/owncloud.log)
No errors

#### Browser log
Indifferent for this issue

**Comment by nickvergessen** [comment]
Can you run these two:
```sql
SELECT COUNT(*) AS num_delete
FROM `oc_activity`
WHERE `timestamp` <= 1433852463
```
```sql
SELECT COUNT(*) AS num_okay
FROM `oc_activity`
WHERE `timestamp` > 1433852463
```

**Comment by enricocanino** [comment]
First query result: 689016
Second query result: 627270

**Comment by enricocanino** [comment]
JUST NOW:
in oc_jobs OCA\Activity\BackgroundJob\ExpireActivities chenged value to: 1435152962
and in oc_activity number of records was decreased.

Means that needs 25 and not 24 hours?

**Comment by nickvergessen** [comment]
Okay, can you try the following:

in app/activity/lib/data.php
find:
```php
	public function deleteActivities($conditions) {
		$sqlWhere = '';
		$sqlParameters = $sqlWhereList = array();
		foreach ($conditions as $column => $comparison) {
			$sqlWhereList[] = " `$column` " . ((is_array($comparison) && isset($comparison[1])) ? $comparison[1] : '=') . ' ? ';
			$sqlParameters[] = (is_array($comparison)) ? $comparison[0] : $comparison;
		}

		if (!empty($sqlWhereList)) {
			$sqlWhere = ' WHERE ' . implode(' AND ', $sqlWhereList);
		}

		$query = DB::prepare(
			'DELETE FROM `*PREFIX*activity`' . $sqlWhere);
		$query->execute($sqlParameters);
	}
```
replace with
```php
	public function deleteActivities($conditions) {
		$sqlWhere = '';
		$sqlParameters = $sqlWhereList = array();
		foreach ($conditions as $column => $comparison) {
			$sqlWhereList[] = " `$column` " . ((is_array($comparison) && isset($comparison[1])) ? $comparison[1] : '=') . ' ? ';
			$sqlParameters[] = (is_array($comparison)) ? $comparison[0] : $comparison;
		}

		if (!empty($sqlWhereList)) {
			$sqlWhere = ' WHERE ' . implode(' AND ', $sqlWhereList);
		}

		$query = DB::prepare(
			'DELETE FROM `*PREFIX*activity`' . $sqlWhere);
		\OC::$server->getLogger()->error(serialize(array('DELETE FROM `*PREFIX*activity`' . $sqlWhere, $sqlParameters)));
		$query->execute($sqlParameters);
	}
```

```sql
UPDATE `oc_jobs` SET `last_run` = 0 WHERE `class` LIKE '%Expire%'
```

and then run your cron, until the expire job does not have last_run set to 0 anymore.
Then please check the owncloud.log file for information.

**Comment by nickvergessen** [comment]
Well the job is queued 24hours after the last run, but when no cron is executed, it may take a while longer.

**Comment by nickvergessen** [comment]
But glad it's fixed.

**Comment by enricocanino** [comment]
Thanks a lot.

:-)
