### ISSUE TITLE
Activity app in app store?

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/activity#320]
I need a little help on the decision here. Currently the activity app has a ocsid entry in the info.xml:
https://github.com/owncloud/activity/blob/master/appinfo/info.xml#L22
all the way down to stable7
https://github.com/owncloud/activity/blob/stable7/appinfo/info.xml#L16

However, in the app store there was only a dummy, so if it would have been used to update the app, it would have killed itself? Anyhow, @LukasReschke removed the dummy yesterday to avoid problems.

Now the question is, should we properly maintain the activity app in the appstore, so people can also update it when they are too lazy to update core with the next maintenance release? Or should we just remove the ocsid everywhere and say that it is only available via the normal packages.

@DeepDiver1975 @karlitschek

**Comment by karlitschek** [comment]
Great point. So in the past we had the idea that it makes sense to be able to push a new version of a shipped app via the app store to replace the originally shipped app like activity.
Nowadays I think this was a stupid idea and I'm also not sure if this feature still works.
My personal opinion is that we should remove this from the shipped app and kill the feature.

**Comment by nickvergessen** [comment]
Okay, I will then go ahead and remove the ocsid from all stable branches and master of the activity app.

**Comment by LukasReschke** [comment]
I created PRs for all other applications. Please review as well.

**Comment by LukasReschke** [comment]
Ah and because somebody thought it would be a good idea to store the OCSID also in the DB but not automatically get a new one if the application has another one in appinfo.xml when updating we also need some other changes. Awesome :rocket:

**Comment by LukasReschke** [comment]
Master: https://github.com/owncloud/core/pull/17316
8.1: https://github.com/owncloud/core/pull/17317
8: https://github.com/owncloud/core/pull/17318
7: https://github.com/owncloud/core/pull/17319

**Comment by LukasReschke** [comment]
@nickvergessen Also requires to bump the version and my PRs against master to work reliably.
