### ISSUE TITLE
Icons for the sidebar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#330]
We should have icons for the sidebar just like in Files. I can’t fix this myself cause the entries are generated via a loop. @nickvergessen can you add classes to the `<a>` elements (_not_ the `<li>`s) like this:
* All activites: nav-icon-activity
* Your activity: nav-icon-yours
* Activity of others: nav-icon-others
* Favorites: nav-icon-favorites
* Shares: nav-icon-sharing

If you open a PR with that I’ll at the icons.

It would be pretty sweet to have this in 8.1 for the proper similar look but I guess this is way too near to the release cc @DeepDiver1975

**Comment by nickvergessen** [comment]
8.1 is already done, 8.1.1 or 8.2, sorry bro

**Comment by nickvergessen** [comment]
Since it will be odd to do something like this in a minor release (we need to extend the public api) I'd say "sorry that we missed it, 8.2 will have it"

**Comment by jancborchardt** [comment]
Ok, works.
