### ISSUE TITLE
Comments starting with '#' are deprecated in ini files

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/activity#342]
Could you please use `//` for line comments?
https://github.com/owncloud/activity/blob/master/tests/usersettingstest.php#L81

**Comment by nickvergessen** [comment]
http://de2.php.net/manual/en/language.basic-syntax.comments.php doesn't say anything about them being deprecated

But sure of course we can change them.

**Comment by szepeviktor** [comment]
Sorry!
This is for comments in *ini* files.
But it is consistent to use slashes for line comments.

**Comment by szepeviktor** [comment]
Sorry!
This is for comments in *ini* files.
But it is consistent to use slashes for line comments.

**Comment by szepeviktor** [comment]
Thank you.
