### ISSUE TITLE
Problem after restoring database and updating to 8.1

### ISSUE THREAD

**Issue by poVoq** [owncloud/activity#345]
I restored a database and upgraded to 8.1 and now all the previous activity entries are shown as 15 years old. Furthermore the entry seems to be partially reversed for some reason, i.e. the '15 year' old entries are always shown at the top. Thus for new users you can still see entries being added at the bottom, but existing users only show a page full of 15 year old entries.

**Comment by karlitschek** [comment]
@nickvergessen any idea?

**Comment by nickvergessen** [comment]
well make sure your server time is correctly configured, other then that without the backup I see no reason for any of this behaviour.

**Comment by poVoq** [comment]
yes, was related to issues with the real time clock and non exisiting internet connections for getting the time from there. Sorry.
