### ISSUE TITLE
User configures German language but receives activity notification mails in English

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/activity#347]
### Steps to reproduce
1. Configure German language
2. Enable Activity app
3. Modify some files
4. Wait for activity notification mails

### Expected behaviour
German language user should receive German activity notification mails

### Actual behaviour
German language user receives English activity notification mails

### Server configuration

**ownCloud version:**
8.0.4

@MorrisJobke 

00003575

**Comment by nickvergessen** [comment]
Was the language configured correctly for each user?

There is special code in place that does grab the language for the users and then sends the email for each user in his language.
See #145 

The only other problem I see is https://github.com/owncloud/core/pull/14650 (linked from previous issue), so they might need to make the adjustment themselves, because we can't backport an API breaking change in a minor release

**Comment by MorrisJobke** [comment]
So this is fixed in 8.1.0. -> close this then as discussed with @michaelstingl :)

**Comment by MorrisJobke** [comment]
Some strings are not translated. I will investigate

**Comment by MorrisJobke** [comment]
In stable8 they were all listed: https://github.com/owncloud/activity/blob/stable8/lib/datahelper.php#L68-L93

**Comment by MorrisJobke** [comment]
It was moved to core: https://github.com/owncloud/core/commit/d20a8fae453bbbf0d254f7af14d5f65681417629 and also translations are present.

**Comment by MorrisJobke** [comment]
Usually it should work :( Somehow it doesn't work here with 8.1.0. It is only partly translated:

```
Hallo USER,

Sie erhalten diese E-Mail, da in der letzten Stunde folgende Dinge bei URL geschehen sind

* user-a hat Hacker-Songs mit Ihnen geteilt - Heute um 12:59:01
* admin hat kbhvjgcfg mit Ihnen geteilt - Heute um 13:58:35
* admin deleted kbhvjgcfg - Heute um 13:59:00
```

All file app related messages aren't properly translated. (see last item)

**Comment by nickvergessen** [comment]
@MorrisJobke you are talking about 8.1 or master? If so please open a new ticket.
The system and stuff changed quite hard in between, in 8.0 everything works fine for me, apart from the https://github.com/owncloud/core/pull/14650 problem

**Comment by MorrisJobke** [comment]
Yes. Seems to be 8.1/master only. On 8.0 there where completely different issues, that are fixed with 8.1+

**Comment by MorrisJobke** [comment]
@nickvergessen Did you fixed it? If so, please reference here

**Comment by nickvergessen** [comment]
No, still waiting for your new issue :wink:

**Comment by MorrisJobke** [comment]
> No, still waiting for your new issue :wink:

-.- Read it the other way around.

**Comment by MorrisJobke** [comment]
#355
