### ISSUE TITLE
interactive activities

### ISSUE THREAD

**Issue by karlitschek** [owncloud/activity#349]
The ownCloud Desktop and Mobile clients should read the activities via the existing OCS API and show them as local activities and push them as notification center event to the local OS. The current sync log on the desktop should be renames as sync log for debugging purpose. The activities that are read from the server are more relevant for the users.

This system is fully implemented on the server and should be implemented on Desktop and Mobile too.

Additionally we want to have a new kind of activities that are called ‘interactive activities’. They provide a way for the server or one of the ownCloud server apps to trigger a minimal interactive UI on the clients.

Every time the clients read an activity from the server OCS activity API that is marked as interactive it should do what is described in the activity. There are different types:

‘popup notification’: This is a notification just like the normal activities but actually triggers a popup on the clients. This can be used for ultra important or fatal events like: Quote is not 100% full and ownCloud doesn’t work anymore. Or the Admin sends a broadcast for server shutdown or some other similar event. The text in the popup is also included in the activity that is read from the server.

‘popup notification with link’: This can be used if for example an authentication token has expired and the user has to go to a certain website to refresh it. Or it can be used to tell the user that a password to access external storage has to be provided in the web-interface. Or that another very important event has occurred where a website can provide more information.

‘question’: This should trigger a popup that has additionally to the text and an optional link two buttons. The text on the buttons is also provided by the server. If the user clicks on a button then an from the server provided url should be called in the background. This can be used to ask the user of a Federation Sharing request should be accepted or denied. 

This kind of interactions with the user on the Desktop or Mobile should be implemented in this very abstract and general purpose way so that they can be used in a flexible way for current and future usecases or ownCloud core or apps.

@nickvergessen @jancborchardt @MTRichards @dragotin @rperezb

**Comment by jancborchardt** [comment]
Ref https://github.com/owncloud/client/issues/1443

**Comment by nickvergessen** [comment]
yeah let me have some thoughts after my vacation

**Comment by dragotin** [comment]
this means implementing a new notification system cross platform, as the current one does not support interactivity unfortunately. @danimo 

I think we should see that under consideration of https://github.com/owncloud/client/issues/1748

**Comment by nickvergessen** [comment]
I had a quick discussion with the task app guys yesterday, they want interactive notifications as well, so they can notify you about a reminder, but also allow "snooze" and "shutdown".

Last week some discussions took place and it was decided to increase activities but make it next to it, because it does not fit in the scope and definition of activities (read log).

**Comment by karlitschek** [comment]
agreed. so this should go into a new 'notification' app

**Comment by jancborchardt** [comment]
cc the Tasks folks for this purpose: @raimund-schluessler @Henni any more feedback except what is already in this thread?

I do agree we need a new »Notifications« app. The only interface should be an icon and popover in the top right. It can then hook in to the clients and apps, and as well show in Activity etc.

**Comment by karlitschek** [comment]
agreed. the only user interface should be the icon and popover in the header.
open question is that all notifications most likely should also be shown in the activity stream. So does an app have to send it to the activity api and the notification api? or does the notification api automatically pass it on to the activity app?

**Comment by jancborchardt** [comment]
I’d say the notification API automatically passing it to the activity app would be good, since every notification is also an activity.

Of course when the notification is »Thomas shared `Vacation pictures` with you [Accept] [Reject]«, then as soon as you accept it the activity shown needs to change accordingly from showing it as interactive notification on top of the Activity list to simply showing it chronologically correct as »Thomas shared `Vacation pictures` with you«.

**Comment by raimund-schluessler** [comment]
I don't know if it is ideal to push a notification from the notification app to the activity app. What happens, when an app implements both activity and notifications? Will I see the entry in the activity stream twice?

**Comment by nickvergessen** [comment]
Woops, didn't ment to close this.

Anyway, the concept will be the other way around. For each activity you can also decide if it should send you a notification, just like with Emails and Stream currently.

The notification app itself will only consist of a Number with dropdown in the header and an Endpoint for the desktop and mobile clients to get the notifications from.

**Comment by nickvergessen** [comment]
https://github.com/owncloud/notifications
