### ISSUE TITLE
User configures German language but receives activity notification emails with some parts in English

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/activity#355]
Some parts of the messages in a activity notification aren't translated. Especially anything that is not related to sharing (deleting files, ...). All file app related messages aren't translated properly.

```
Hallo USER,

Sie erhalten diese E-Mail, da in der letzten Stunde folgende Dinge bei URL geschehen sind

* user-a hat Hacker-Songs mit Ihnen geteilt - Heute um 12:59:01
* admin hat kbhvjgcfg mit Ihnen geteilt - Heute um 13:58:35
* admin deleted kbhvjgcfg - Heute um 13:59:00
```
ref #347 

ownCloud version: 8.1.0+

cc @michaelstingl 00003575

**Comment by michaelstingl** [comment]
@MorrisJobke Thank you for connecting me with the new issue.

**Comment by MorrisJobke** [comment]
@michaelstingl will be fixed in 8.1.2

**Comment by kiu-ball** [comment]
Still have this problem in 8.1.3. Language is set to 'Deutsch (Förmlich: Sie)'.

**Comment by nickvergessen** [comment]
Please try 8.1.4 and/or 8.2
