### ISSUE TITLE
Append etag in preview URLs

### ISSUE THREAD

**Issue by PVince81** [owncloud/activity#369]
I got a case where the URL returned by the activity app was showing the wrong cached preview from an older version of the file.

Ideal would be to either append a random string "c=1a2b3c4d5" in the URL or the etag.

**Comment by nickvergessen** [comment]
No, that's abuse against caching. If the valid preview URL returns a wrong image, that is something core has to deal with!

**Comment by PVince81** [comment]
Using the etag isn't abuse. We do that in the files app too.
So as long as the file is the same as before, it will use the cached image from the browser as it has the same etag.
If the etag changes, a new preview is requested.

**Comment by PVince81** [comment]
(a random string is abuse, yes)

**Comment by nickvergessen** [comment]
Well, currently we don't have the etag. Maybe  as part of chaning previews to file id way

**Comment by PVince81** [comment]
Isn't the preview URL bundled in a field ? You could just append the etag there.

**Comment by nickvergessen** [comment]
No it is currently generated from the file path. But that means when it is moved we don't have previews anymore, so changing that is maybe a good idea anyway.
