### ISSUE TITLE
Add html version of "activity notification mail"

### ISSUE THREAD

**Issue by rakekniven** [owncloud/activity#370]
Reading long "activity notification mail" in plain text is not nice.
Please add html version of notification and add it to template editor.
Each item (modified/added/deleted) should contain html link to directly call item.

A good example can be seen on how Alfresco is doing it.

I can add example after returning to work.

**Comment by rakekniven** [comment]
Here is my example from an alfresco DMS system:
![recent activities](https://cloud.githubusercontent.com/assets/2069590/9631814/cbc7408e-5183-11e5-9e2f-2e7effe40197.PNG)

Please see hyperlinks. 
You can click on user to see public user profile. Don't know if we have a target for this on an ownCloud system at the moment.
You can click each item (folder or file) to get directly to suitable web location.
Report is very ease to read IMHO. Even when it is bigger.
On the bottom there is direct link
Also note link at the bottom to get directly to notifications settings.

**Comment by partyisover** [comment]
:+1: 
is there a way to add file links to the existing mail template? html parsing doesn't work for me.
