### ISSUE TITLE
Activity tab in sidebar shows preview icon for every action

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#377]
There’s really no need to show the preview icon for every action like sharing. The only cases where it should be shown is for creation and for changes.

@nickvergessen

**Comment by jancborchardt** [comment]
@nickvergessen change action doesn’t show a thumbnail though. For images that should happen (so you can compare old and new.

**Comment by nickvergessen** [comment]
Not possible, because versions app is not required to be there and version an expire and versions are not linked to activities and there is no public api that gives you a preview for a file at a given timestamp.

**Comment by jancborchardt** [comment]
Can we then introduce this in the versions app and make it an optional enhancement when it’s present? cc @schiesbn @blizzz

**Comment by jancborchardt** [comment]
…

**Comment by jancborchardt** [comment]
@nickvergessen can you please sit together with whomever is responsible for the Versions app to make this happen?
