### ISSUE TITLE
Activity tab in sidebar doesn’t show activity inside folder

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#380]
Even though @nickvergessen told me this is basically impossible, here’s an issue for it.

When I open the details pane of a folder, I want to know the activity of what happened inside it. Currently only creation and sharing is shown (in the future rename). I definitely expect to see all activity of files inside it right there.

cc @DeepDiver1975

**Comment by nickvergessen** [comment]
This can only be implemented, if the file tree is stored in a different way in the database of OC. We can get a list of files below the folder, but recursively getting all of them and all activities for them is not going to be nice, so this won't happen.
