### ISSUE TITLE
Blurry icons with new icons of core

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/activity#381]
![bildschirmfoto von 2015-08-29 13-47-20](https://cloud.githubusercontent.com/assets/245432/9561783/99a37dd4-4e54-11e5-8e9c-155164ed404a.png)

core master

cc @jancborchardt

**Comment by nickvergessen** [comment]
The problem is, that the preview is not the SVG, but the preview system returns the mimetype icon as an image instead of telling that there is no preview

**Comment by nickvergessen** [comment]
Core is replying wrong as per above.
I digged a bit into it: owncloud/core#18655
