### ISSUE TITLE
Text of activity notification mail doesn't fit to send cycles

### ISSUE THREAD

**Issue by rakekniven** [owncloud/activity#387]
e.g. mail contains following statement in body:
You are receiving this email because in the last day the following things happened at xxx

If you send out notifications hourly it should be:
You are receiving this email because in the last hour the following things happened at xxx

for weekly settings you better say:
You are receiving this email because in the last week the following things happened at xxx

Another solution would be to be more general:
You are receiving this email because ~~in the last day~~ the following things happened at

**Comment by rakekniven** [comment]
The german translation is even whore for hourly setting:
"Sie erhalten diese E-Mail, da gestern folgende Dinge bei xxx geschehen sind"

Where to report? Maybe some german natives are around ;-)

**Comment by nickvergessen** [comment]
Yeah removing sounds like a good idea, that will solve issues with translations more easily.

**Comment by rakekniven** [comment]
How to get along with this.
Am I allowed to change that string at transifex?

**Comment by nickvergessen** [comment]
You can send a Pull Request against this repository changing it here:
https://github.com/owncloud/activity/blob/master/templates/email.notification.php#L10-L16

transifex will then be automatically updated. I will try to find time on monday to do it, in case you don't want to.
