### ISSUE TITLE
Reduce amount of text in activity sidebar, don’t show filename on every change

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#395]
Currently in every single entry the filename is mentioned. This is way too much clutter in the sidebar where we don’t have much space and info should not be redundant anyway.
(Ignore the missing share icons please, that’s caused by my adblocker.)
![capture du 2015-09-17 14-19-49](https://cloud.githubusercontent.com/assets/925062/9932835/4159b3f8-5d47-11e5-9e09-a92432d58f15.png)
Here’s some better wording. Of course we can only use it here in the file-specific view, not in the Activity app.
![capture du 2015-09-17 14-19-15](https://cloud.githubusercontent.com/assets/925062/9932836/415cd90c-5d47-11e5-8bc1-7d002730e739.png)

@owncloud/designers @nickvergessen

**Comment by jancborchardt** [comment]
(Btw it’s even worse in mobile mode when the text starts wrapping just because the filename is mentioned every time.)

**Comment by PVince81** [comment]
I believe that the full text is stored in the database, so it cannot easily be removed unless the format of the (future) messages is changed to always be short, and let the JS code augment them ?

@nickvergessen

**Comment by nickvergessen** [comment]
> I believe that the full text is stored in the database, so it cannot easily be removed unless the format of the (future) messages is changed to always be short, and let the JS code augment them ?

This was the case, but was changed in oc7 :frowning: 

But this will never the less be quite taff, since we need to tunnel the information which screen we are on all the way through.

**Comment by PVince81** [comment]
You might be able to detect whether we are filtering by file id, and when it is then remove the file name from the message (if possible).

**Comment by nickvergessen** [comment]
yeah as said, that info needs to be tunneled through the public api :no_mouth: 

Will have a look tomorrow

**Comment by jancborchardt** [comment]
@nickvergessen did you have a look then?

**Comment by nickvergessen** [comment]
Only quick, will try to work on this, once all the other 8.2 tasks that are more important are done

**Comment by jancborchardt** [comment]
Thanks! :) It’s quite a big visual point in one of our most prominent features, so it would be good to get that to look proper.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct
