### ISSUE TITLE
Strange activity message flood

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/activity#397]
![capture du 2015-09-17 19-31-04](https://cloud.githubusercontent.com/assets/925062/9941357/1a2be67e-5d75-11e5-8d84-cccc87d74d4f.png)

I get one of each of these messages _every time_ I share via link, or just »allow editing«. There should only be one activity of course, and the technical id there is wrong. … @nickvergessen

**Comment by jancborchardt** [comment]
cc @schiesbn cause of sharing

**Comment by nickvergessen** [comment]
Missing translations are due to https://github.com/owncloud/core/pull/18679 which just needs merge.

Will have a look at the duplication thou

**Comment by nickvergessen** [comment]
Fix is at https://github.com/owncloud/activity/issues/398
