### ISSUE TITLE
Others Activity: show everybody, not inner circle. Privacy Issue

### ISSUE THREAD

**Issue by stevejordi** [owncloud/activity#404]
### Steps to reproduce
1. Log in (non admin account)
2. Activity
3. All activity

### Expected behaviour
Show all activity from accounts you interact with.

### Actual behaviour
Shows activity from all accounts, no matter what.
Privacy issue.

### Server configuration
**Operating system**: CentOS 6.7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.6.13

**ownCloud version:** 8.1.0

**Updated from an older ownCloud or fresh install:**
Fresh install.
Data imported from version 7.
occ upgrade to set things straight.

**List of activated apps:**
FirstRun Wizard 1.1
LDAP Users & Groups backend 0.6.1
Mail Template Editor 0.1
PDFViewer 0.7
Pictures 0.6.0
Share Files 0.6.2
TextEditor 0.4
Updater 0.6
Versions 1.0.6
Video Viewer 0.1.3
Contacts 0.4.0.0

**The content of config/config.php:**

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)
Can't provide it

### Client configuration
**Browser:** All

**Operating system:** All

**Comment by karlitschek** [comment]
Can you post exactly how to reproduce this? The idea is to see activities on files that are a shared with others.

**Comment by nickvergessen** [comment]
We only show activities of files you can see. That is exactly what the purpose of the activity app is.
If the activity is for a file you can not see, then this would be a "privacy bug". In which case you should not have posted this public. But I can't reproduce this, so I think you only "misunderstood" how the app is supposed to work?

**Comment by stevejordi** [comment]
As said:
- log to account
- select "Activity" from the menu
- on the left submenu bar, click "Activities by others"
Then you have ALL activities from EVERYBODY in the organization, 2000 in my case, not the only 10 persons I deal with.

I'm a system and software engineer since 1980... so I guess I know what I'm talking about.
This is not misunderstanding how the app works.
I agree that this menu should show only the activity of your inner circle, with whom you have contacts, shared links, etc... This is not the case.
I see activities and file names from the entire community, people I don't know, and with whom I never shared anything.
This is not related to my account. Everybody sees everybody. 
For now we have disabled the activity app to avoid legal action against us (we have very strong privacy laws here in Switzerland).

**Comment by karlitschek** [comment]
so do you see files mentioned that you can't access?

**Comment by LukasReschke** [comment]
> Fresh install.
> Data imported from version 7.

Also how did you import the data?

**Comment by stevejordi** [comment]
Yes, I see doc names I can't access.

Regarding the import from own cloud 7
- snapshot of data files + MySql
- copied the data files to the new machine
- copied the database to the new machine
- applied rights to folders
- occ upgrade (which returned no errors)

**Comment by nickvergessen** [comment]
I can not reproduce any such issue, do you have database access, so you can check whether the affected_user is you, or someone else?

**Comment by stevejordi** [comment]
if I select affecteduser from oc_activity, I have 12359 rows with all users

**Comment by stevejordi** [comment]
select distinct affecteduser from oc_activity returns a list of all accounts, 2098 rows.

**Comment by nickvergessen** [comment]
and does it show activities to you, which have affected user set to "not you"

**Comment by stevejordi** [comment]
What do you mean? How can I do this?

**Comment by nickvergessen** [comment]
```sql
select subject from oc_activity where affecteduser = '<your name>'
```

And see if it matches the list you see in the UI

**Comment by stevejordi** [comment]
I get only the kind of actions "deleted", "shared with", etc... I have 358 shares. 
What I did though was to disable Activity. Then enable it back and things seem to have improved now.
But we all still have some activities that are not at all related to our own activities... but not by the thousands. We do have the file name details of the operations though.

**Comment by nickvergessen** [comment]
> But we all still have some activities that are not at all related to our own activities

They don't need to, if they are for a file you see, you are a valid recipient of the activity.

**Comment by stevejordi** [comment]
Sorry but no.
I have activities I should not see. Those files have not been shared with me or a group I belong to.
I should not even know that person A has shared, added or deleted a private file shared with someone else.

This is a privacy flaw.
I have to fully disable “Activity” in order to avoid legal actions. That’s what it is.
Now if you don’t want to see the reality that’s another thing.

**Comment by karlitschek** [comment]
it is a feature of the activities app to show all activities on files that i own or are shared with me. 

if you don't want this functionality then just disable the app. case closd.

**Comment by stevejordi** [comment]
A and B share a file.
C and D share a file between them.
A and B don’t know C or D and have no relations with them.

Why would A be aware of C and D and their filename? A and B have nothing to do with C and D?

Steve

**Comment by nickvergessen** [comment]
I can not reproduce something like that.

However if A shares a file of C to B, then C will see file changes of B on that file.

**Comment by LukasReschke** [comment]
@stevejordi This seems like a privacy related bug that may require some direct support by us. - Can you get in touch with me privately? 

-> lukas(at)owncloud(dot)com

**Comment by stevejordi** [comment]
I totally understand this.
But if A shares with B.
C shares with everybody but A and B, and those everybody to re-share that C file with A and B, those latter have no reason to be informed about someone outside activities.

That’s my point.
That’s why we can’t use that activity which is something required for a lot of people.

Steve
