### ISSUE TITLE
API: String entries are not localized

### ISSUE THREAD

**Issue by dragotin** [owncloud/activity#406]
The API returns strings in the `subject` and the `message` tag at least. These are in an english locale, not translated.

If I read the code correctly, there is no way for the client to specify the language the server should return. That could either be done with an additional parameter, or, via the `Accept-Language` header as described here: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

This blocks https://github.com/owncloud/client/issues/3732

**Comment by nickvergessen** [comment]
They are translated with the language the user selected in the web UI, should be sufficient?

**Comment by dragotin** [comment]
No, I do not think so. Client- and server language settings have nothing to do with each other.

**Comment by nickvergessen** [comment]
I guess the number of people that have client and server set to different languages is pretty low, but I can try to read the language from the accept-language header, if you think it is really necessary.

**Comment by dragotin** [comment]
Yes, I think that. There seems to be a considerable number of people who never open the web interface but only sync in large organizations. An example might be an US company with a branch in china, they will have an english server by default, but the desktops of the people will be in their locale. 

I don't think we want to force them to go to their personal settings on a for them unknown website first (in a language they do not understand) to switch. It's the small things that make a good software perfect ;-)

**Comment by DeepDiver1975** [comment]
The language is already taken from the Accept-Language header in core

**Comment by nickvergessen** [comment]
yeah just found that as well and it works for me using curl, when I hardcode the value in https://github.com/owncloud/core/blob/master/lib/private/l10n.php#L107 and https://github.com/owncloud/core/blob/master/lib/private/l10n.php#L113

**Comment by DeepDiver1975** [comment]
```sh

$ curl -H "Accept-Language:de;q=0.8" http://admin:admin@localhost:8080/ocs/v1.php/cloud/activity
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <element>
   <id>10</id>
   <subject>Du hast IMG_2003.JPG, IMG_2004.JPG, IMG_2020.JPG und 3 weitere erstellt</subject>
   <message></message>
   <file>/IMG_2003.JPG</file>
   <link>http://localhost:8080/index.php/apps/files?dir=%2F</link>
   <date>2015-10-08T10:38:46+00:00</date>
  </element>
  <element>
   <id>4</id>
   <subject>Du hast IMG_2035.JPG, IMG_2110.JPG, IMG_2148.JPG und IMG_2165.JPG erstellt</subject>
   <message></message>
   <file>/IMG_2035.JPG</file>
   <link>http://localhost:8080/index.php/apps/files?dir=%2F</link>
   <date>2015-10-08T10:38:19+00:00</date>
  </element>
 </data>
</ocs>
deepdiver@alien:~/Development/ownCloud/master/apps3 [master]$ curl -H "Accept-Language:es;q=0.8" http://admin:admin@localhost:8080/ocs/v1.php/cloud/activity
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <element>
   <id>10</id>
   <subject>Ha creado IMG_2003.JPG, IMG_2004.JPG, IMG_2020.JPG y 3 más</subject>
   <message></message>
   <file>/IMG_2003.JPG</file>
   <link>http://localhost:8080/index.php/apps/files?dir=%2F</link>
   <date>2015-10-08T10:38:46+00:00</date>
  </element>
  <element>
   <id>4</id>
   <subject>Ha creado IMG_2035.JPG, IMG_2110.JPG, IMG_2148.JPG y IMG_2165.JPG</subject>
   <message></message>
   <file>/IMG_2035.JPG</file>
   <link>http://localhost:8080/index.php/apps/files?dir=%2F</link>
   <date>2015-10-08T10:38:19+00:00</date>
  </element>
 </data>
</ocs>

**Comment by DeepDiver1975** [comment]
from my pov this can be closed since it's working

**Comment by dragotin** [comment]
Yes, thanks & my apologies. I tested with 8.0.x where it's not yet working...
