### ISSUE TITLE
Wrong link and missing information

### ISSUE THREAD

**Issue by cdamken** [owncloud/activity#410]
1) Upload a file to oC
2) Move the file to a new folder
3) Go to Activity log
4) Activity log says "You created XXX.jpg" and allows you to click on it
5) Click on it and it brings you to the original location -- where the file no longer exists
6) Activity log says nothing about the files being moved

Also:
1) Share File A with me
2) Unshare File A with me
3) Activity log shows the SHARE but not the unshare

oC8.1.3

**Comment by nickvergessen** [comment]
Yeah, that is currently by design

**Comment by nickvergessen** [comment]
Related #262
