### ISSUE TITLE
Make configurable how long notifications are stored

### ISSUE THREAD

**Issue by tflidd** [owncloud/activity#417]
Currently it seems that owncloud stores activity notifications for 1 year (the oldest entry I found is exactly one year old). Unfortunately, my table has grown to 69 MB (123000) entries over time.

During the latest update from OC 8.0.6 to 8.0.8, it took 3 minutes to create a temporary copy and alter this table twice.

Is there any way to configure how long these notifications stay in the database. Is there a particular reason to keep them 1 year?

**Comment by nickvergessen** [comment]
Already exists since owncloud 7:
https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/config_sample_php_parameters.html#app-config-options

**Comment by tflidd** [comment]
@nickvergessen I only checked config.sample.php, maybe you should add it there as well.

**Comment by nickvergessen** [comment]
It was decided against putting app values into the core sample, because apps may or may not be there and the config in the sample then be of no-use and only confusing for admins.
