### ISSUE TITLE
Upgrade 8.1.x -> 8.2: Missing schema-update for table oc_activity

### ISSUE THREAD

**Issue by umgfoin** [owncloud/activity#420]
During the schema update from 8.1.x to 8.2 table "oc_activity" wön't get correctly upgraded:
Columns "object_id" and "object_type" are not created.
Column "user" declared with "NOT NULL" constrains is violated with NULL-inserts.
Disabling the activity-app and deleting "oc_activity"-table doesn't fix the issue.

The incorrect "oc_activity" table breaks functionality not directly related to activity-tracking:
E.g. opening a public shared pdf-link fails.

Inserting the missing columns and removing the NOT NULL restriction fixes the problem.
Verified on Postgres-backend only.

bg umgfoin.

**Comment by karlitschek** [comment]
can you please post a full bug report using the issue template? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by nickvergessen** [comment]
You didn't update your instance correctly
https://github.com/owncloud/activity/issues/419#issuecomment-149830559
