### ISSUE TITLE
OC 8.2 No Email Notification etc.

### ISSUE THREAD

**Issue by apg1980** [owncloud/activity#421]
Hello together,

here my environment:
Bitnami OC 8.2 Stack
Ubuntu 14.04
Apache to 2.4.17
PHP to 5.5.29
MySQL to 5.6.25

after uploading files via webfrontend no entry within the activity app. deleted files are shown in the activity app.
i can see the uploadet file in oc_activity table.

no emial notification is coming. alle email options in personal tab are set.

**Comment by nickvergessen** [comment]
Did you set up your actual user email address on the personal page?
And are the email admin settings set up correctly?

**Comment by apg1980** [comment]
yes i get this via ldap. same config on 8.1.3 was wirking flawlessly

**Comment by nickvergessen** [comment]
Are the entries added to the activity_mq table?

**Comment by apg1980** [comment]
yes all entrys are in.
but alle the time i upload some files via webpage i get no mail notification althought setted hourly mail notification. for other purposes i get the notification. i cannot see my own actions in action app.

**Comment by nickvergessen** [comment]
Can you please post the result of
```sql
SELECT *
FROM `oc_jobs`
ORDER BY `class` ASC
```

**Comment by apg1980** [comment]
Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	9917 	OCA\Activity\BackgroundJob\EmailNotification 	null 	1446040842
	Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	8322 	OCA\Activity\BackgroundJob\ExpireActivities 	null 	1446010201
	Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	9912 	OCA\Files_Trashbin\BackgroundJob\ExpireTrash 	null 	1446040842
	Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	9913 	OCA\Files_Versions\BackgroundJob\ExpireVersions 	null 	1446040842
	Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	9499 	OCA\Files_sharing\Lib\DeleteOrphanedSharesJob 	null 	1446039901
	Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	3 	OCA\user_ldap\lib\Jobs 	null 	1446040801
	Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	9911 	OC\BackgroundJob\Legacy\RegularJob 	["OCA\\News\\Cron\\Updater","run"] 	1446040801
	Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	0 	OC\Log\Rotate 	"\/OWNCLOUD-DATA\/opt\/data\/owncloud.log" 	1446040801
	Bearbeiten Bearbeiten 	Kopieren Kopieren 	Löschen Löschen 	8321 	\OCA\User_LDAP\Jobs\CleanUp 	null 	1446039901

**Comment by nickvergessen** [comment]
Looks good, the email cron was executed today. Can you visit the admin panel and try to send a test email, using the `Test email settings` option?

**Comment by apg1980** [comment]
i am getting email messages, but not from my own actions via the webfrontend.

**Comment by nickvergessen** [comment]
Which actions exactly?

**Comment by apg1980** [comment]
for example, i am uploading a file via the webfrontend to my account, no entry in activity. this is reproduceable.

**Comment by nickvergessen** [comment]
> Hello admin,
>
> You are receiving this email because the following things happened at http://localhost/8.2/
> 
> * You created image001.png - Today at 9:06:42 AM

Works just fine for me.
Please make sure that you have your personal email settings right:
![personal_-_owncloud_-_2015-11-03_09 09 14](https://cloud.githubusercontent.com/assets/213943/10903528/ef53913a-820a-11e5-9efc-55eefedaf11c.png)

As well as the notification settings:
![personal_-_owncloud_-_2015-11-03_09 09 32](https://cloud.githubusercontent.com/assets/213943/10903533/f6b5823a-820a-11e5-8929-0f80eae1ddd3.png)

And the email system itself (test with the button):
![admin_-_owncloud_-_2015-11-03_09 09 50](https://cloud.githubusercontent.com/assets/213943/10903537/020ca244-820b-11e5-9bf7-9b27d013993d.png)

Other then that I can not reproduce it and help you.

**Comment by apg1980** [comment]
all the options are set, and also the send email test is working.

**Comment by nickvergessen** [comment]
Well then check your spam folder, nothing I can help you with.
