### ISSUE TITLE
Expiring takes a long time

### ISSUE THREAD

**Issue by scolebrook** [owncloud/activity#423]
I'm running 8.1.3 and have about 10,000,000 rows in the activity table. It takes about 2 minutes to run the delete from oc_activity where `timestamp`<? query in the expiry job even if there are no rows that need to be deleted. An explain on that query shows that there are no indexes being used. However I see timestamp is part of 3 other indexes.

However if the cron job doesn't run for a few days for whatever reason, there are so many records that do need to be deleted that this query takes forever.

Should timestamp be in the primary key or be it's own index to speed up this delete operation? Perhaps someone with more MySQL experience could comment?

**Comment by nickvergessen** [comment]
Primary in no way, but will have a look. I thought I made sure it uses an index....

**Comment by nickvergessen** [comment]
https://github.com/owncloud/activity/pull/424 Feel free to add the index yourself
