### ISSUE TITLE
Shared file access gets postgres error: Undefined column: 7 ERROR: object_type

### ISSUE THREAD

**Issue by westberliner** [owncloud/activity#431]
On Owncloud 8.2.0.12
Activity App 2.1.3
With Postgres 9.4.4

If i disable the activity app sharing works again.

I get following error while accessing sharelink:

> {"reqId":"LLQboElKwM9u6Ao7G3x7","remoteAddr":"172.17.0.4","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'INSERT INTO \\\"oc_activity\\\" (\\\"app\\\", \\\"subject\\\", \\\"subjectparams\\\", \\\"message\\\", \\\"messageparams\\\", \\\"file\\\", \\\"link\\\", \\\"user\\\", \\\"affecteduser\\\", \\\"timestamp\\\", \\\"priority\\\", \\\"type\\\", \\\"object_type\\\", \\\"object_id\\\") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\\\"files_sharing\\\", \\\"public_shared_file_downloaded\\\", \\\"[\\\\\\\"\\\\\\\\\\\\\\\/Screen Shot 2015-10-30 at 17.09.23.png\\\\\\\"]\\\", \\\"\\\", \\\"[]\\\", \\\"\\\\\\\/Screen Shot 2015-10-30 at 17.09.23.png\\\", \\\"\\\", null, \\\"wbadmin\\\", 1447065929, 30, \\\"public_links\\\", \\\"\\\", 0]:\\n\\nSQLSTATE[42703]: Undefined column: 7 ERROR:  column \\\"object_type\\\" of relation \\\"oc_activity\\\" does not exist\\nLINE 1: ... \\\"affecteduser\\\", \\\"timestamp\\\", \\\"priority\\\", \\\"type\\\", \\\"object_ty...\\n                                                             ^\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO \\\"oc...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/db\\\/connection.php(203): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO \\\"oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(121): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/activity\\\/lib\\\/data.php(126): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/html\\\/apps\\\/activity\\\/lib\\\/consumer.php(74): OCA\\\\Activity\\\\Data->send(Object(OC\\\\Activity\\\\Event))\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/activitymanager.php(188): OCA\\\\Activity\\\\Consumer->receive(Object(OC\\\\Activity\\\\Event))\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/activitymanager.php(215): OC\\\\ActivityManager->publish(Object(OC\\\\Activity\\\\Event))\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/controllers\\\/sharecontroller.php(288): OC\\\\ActivityManager->publishActivity('files_sharing', 'public_shared_f...', Array, '', Array, '\\\/Screen Shot 20...', '', 'wbadmin', 'public_links', 30)\\n#10 [internal function]: OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->downloadShare('XlaVhSKAG55RJXP', NULL, '', '')\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/html\\\/lib\\\/public\\\/appframework\\\/app.php(134): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#15 \\\/var\\\/www\\\/html\\\/core\\\/routes.php(124): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#16 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(Closure), Array)\\n#18 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/s\\\/XlaVhSKAG55R...')\\n#19 \\\/var\\\/www\\\/html\\\/index.php(39): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":72}","level":3,"time":"2015-11-09T10:45:29+00:00"}

I recently updated from 8.0 to 8.2 any clues how to fix this?

Thx!

**Comment by nickvergessen** [comment]
You didn't update your instance correctly
https://github.com/owncloud/activity/issues/419#issuecomment-149830559

---

You didn't delete the old files and just uploaded the new files into the existing folder.

https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Comment by westberliner** [comment]
Thx. The update fixed this. I will split my appfolder from coreappfolder from now on.

**Comment by pioneerwebsites** [comment]
We use Installatron to update, so they are apparently doing the update incorrectly... :-(
