### ISSUE TITLE
Activity on shared external storage does show no/incorrect file/folder names

### ISSUE THREAD

**Issue by swurzinger** [owncloud/activity#433]
### Steps to reproduce
1. Set up Google Drive as external Storage. In my case I was accessing via a shared (sub)folder
2. Upload some files to that folder
3. Go to activity log

### Expected behaviour
File/Foldernames should be shown

### Actual behaviour
Incorrect or no file/foldernames are shown:
![activitylog](https://cloud.githubusercontent.com/assets/6787397/11122631/5955d716-895c-11e5-930e-f03c21d6d2e2.png)

A folder name "MVL" exists, but not "MVLdf", "MVLPG" and so on. The files were actually uploaded to a subfolder of the "MVL" folder.

The folder structure looks like this:

User "admin":
/GDrive           mountpoint for Google Drive external storage
/GDrive/MVL        subfolder on Google Drive storage, shared to user "mvl"

User "mvl":
/MVL             shared folder from user "admin"

### Server configuration
**Operating system**:
Linux af91f 2.6.32-504.8.1.el6.x86_64 
**Web server:**
Apache (unknown version; shared hosting provider)
**Database:**
5.5.46 - MySQL Community Server
**PHP version:**
PHP Version 5.4.45
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.0 (stable) 
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
default + external storage (files_external)

**The content of config/config.php:**
[config.txt](https://github.com/owncloud/core/files/33002/config.txt)

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, Google Drive.

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 42, IE 11

**Operating system:**
Windows 8.1 x64

#### Web server error log
empty

#### ownCloud log (data/owncloud.log)
empty

#### Browser log
empty

**Comment by nickvergessen** [comment]
Duplicate https://github.com/owncloud/core/issues/15858
