### ISSUE TITLE
Lazy loading doesn't work 

### ISSUE THREAD

**Issue by enoch85** [owncloud/activity#441]
Since 8.2.1 Lazy loading doesn't work any more. 

Check video for desciption.
https://en0ch.se/index.php/s/rjuKBf4iFgFBsaN

#### Server
Ubuntu 14.04
PHP 5.6
MySQL 5.5

**Comment by nickvergessen** [comment]
Anything in the log, js console, network tab of yout browser?
And the loading seems to work at least a bit, because it shows more then 30 entries?

**Comment by enoch85** [comment]
@nickvergessen There is no distinct error in the logs AFAIK. And the number of items are inconsistent. On the "All activites" it seems to work on the first 30, then it breaks somewhere around 50. Only thing I can find is this in the network console:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /themes/custom/core/img/actions/settings.svg was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at en0ch.se Port 443</address>
</body></html>
```

But even after I solved that, the issue remains the same. No other errors in the browser console.

Hard bug to solve without any info, I know.  I've tried on different production servers that run 8.2.2 and they are all the same.

**Comment by enoch85** [comment]
@nickvergessen I can give you an account if you want to try for yourself?

**Comment by nickvergessen** [comment]
> I can give you an account if you want to try for yourself?

Would be nice, poke me on IRC?

**Comment by nickvergessen** [comment]
Master is currently also affected, but will be fixed with #434 differently

**Comment by enoch85** [comment]
Works! :+1:  Thank you!

**Comment by enoch85** [comment]
> Would be nice, poke me on IRC?

Problem solved, no need. :)

**Comment by enoch85** [comment]
Close via PR instead.
