### ISSUE TITLE
German translation...

### ISSUE THREAD

**Issue by jpaechnatz** [owncloud/activity#447]
Cause I don't want to open a transifex account for one translation error...could somebody please change "erhälst" in "erhältst". Thanks. 

Concerning files:
apps/activity/l10n/nds.json
apps/activity/l10n/de.json
apps/activity/l10n/nds.js
apps/activity/l10n/de.js

**Comment by nickvergessen** [comment]
done for de, waiting for approval to nds

**Comment by nickvergessen** [comment]
Both entries will be fixed with the next transifex update tonight.
