### ISSUE TITLE
No BackgroundJob\EmailNotification

### ISSUE THREAD

**Issue by zarakiel** [owncloud/activity#453]
Hello,

I run an Owncloud server 8.2.2 on a Linux Debian 8.
The activity app is functioning except the mail notifications.
The owncloud mail function is configured correctly and I receive test mails.

When I look into the DB I can see the activities in oc_activity_mq but no EmailNotification in oc_jobs...

Do someone know what I can do ?

Thanks :)

**Server configuration**
Operating system: Linux Debian 8
Web server: Apache
Database: SQlite
PHP 5.6.14-0+deb8u1
ownCloud version: 8.2.2

*List of activated apps:* standard

**config/config.php**
```json
{
    "system": {
        "instanceid": "octh77ou3z7d",
        "passwordsalt": " REMOVED SENSITIVE VALUE ",
        "secret": " REMOVED SENSITIVE VALUE ",
        "datadirectory": " REMOVED SENSITIVE VALUE ",
        "overwrite.cli.url": "https:\/\/ REMOVED SENSITIVE VALUE ",
        "dbtype": "sqlite3",
        "version": "8.2.2.2",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": " REMOVED SENSITIVE VALUE ",
        "mail_domain": " REMOVED SENSITIVE VALUE ",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": " REMOVED SENSITIVE VALUE ",
        "mail_smtpport": "465",
        "mail_smtpname": " REMOVED SENSITIVE VALUE ",
        "mail_smtppassword": " REMOVED SENSITIVE VALUE ",
        "activity_expire_days": 365,
        "loglevel": 0,
        "maintenance": false
    }
}
```

*Are you using external storage, if yes which one:* no
*Are you using encryption:* no
*Are you using an external user-backend, if yes which one:* no

**Comment by nickvergessen** [comment]
Might be caused by a failure when sending an email.
In the past background jobs got removed when they failed.

Until the next maintenance update you can add the following at the end of the `apps/activity/appinfo/app.php` file:
```php
\OC::$server->getJobList()->add('OCA\Activity\BackgroundJob\EmailNotification');
\OC::$server->getJobList()->add('OCA\Activity\BackgroundJob\ExpireActivities');
```

Or you apply the patch: https://github.com/owncloud/core/commit/6b813f56c9208743002456792009dd14b950b8d3 and add the entries manually back to the jobs table.
