### ISSUE TITLE
[8.2.2] "InvalidFieldNameException" by trying to download a public shared file

### ISSUE THREAD

**Issue by RalfWW** [owncloud/activity#454]
### Steps to reproduce
1. create a folder with some files
2. share this folder "by Link" with password and allow modification
3. Access OC by the created Link, type the password and try to download a file

4. Deactivating the App "Activity": the download starts as expected.

### Expected behaviour
Tell us what should happen
The download window shoud start

### Actual behaviour
Tell us what happens instead
"... A server error occures ..."

### Server configuration
**Operating system**:
Linux
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.6
Server running as WEB-Hosting at Strato
**ownCloud version:** (see ownCloud admin page)
8.2.2
**Updated from an older ownCloud or fresh install:**
Update from 8.2.1
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Activity 2.0.2
Deleted Files 0.6.3
File Locking
Share Files 0.6.2
Calendar 0.8.1
Contacts 0.5.0.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
```

### Client configuration
**Browser:**
Firefox 43.0.4
**Operating system:**
Win 7 prof SP1
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"Vqj4r8CoKK8AAEEEYooAAAD@","remoteAddr":"84.175.130.199","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\\\"files_sharing\\\", \\\"public_shared_file_downloaded\\\", \\\"[\\\\\\\"\\\\\\\\\\\\\\\/sync\\\\\\\\\\\\\\\/public\\\\\\\\\\\\\\\/2015-12-05_B-C-D\\\\\\\\\\\\\\\/Bilder\\\\\\\\\\\\\\\/0_quisma_Mazda_CX5_mobile_154x154[1].gif\\\\\\\"]\\\", \\\"\\\", \\\"[]\\\", \\\"\\\\\\\/sync\\\\\\\/public\\\\\\\/2015-12-05_B-C-D\\\\\\\/Bilder\\\\\\\/0_quisma_Mazda_CX5_mobile_154x154[1].gif\\\", \\\"\\\", null, \\\"me@ownclud\\\", 1453914289, 30, \\\"public_links\\\", \\\"\\\", 0]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'field list'\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/db\\\/connection.php(203): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array, Array)\\n#4 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(121): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/apps\\\/activity\\\/lib\\\/data.php(126): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/apps\\\/activity\\\/lib\\\/consumer.php(74): OCA\\\\Activity\\\\Data->send(Object(OC\\\\Activity\\\\Event))\\n#7 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/activitymanager.php(188): OCA\\\\Activity\\\\Consumer->receive(Object(OC\\\\Activity\\\\Event))\\n#8 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/activitymanager.php(215): OC\\\\ActivityManager->publish(Object(OC\\\\Activity\\\\Event))\\n#9 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/apps\\\/files_sharing\\\/lib\\\/controllers\\\/sharecontroller.php(289): OC\\\\ActivityManager->publishActivity('files_sharing', 'public_shared_f...', Array, '', Array, '\\\/sync\\\/public\\\/20...', '', 'me@ownclud', 'public_links', 30)\\n#10 [internal function]: OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->downloadShare('Z39mIaB5HT76630', '0_quisma_Mazda_...', '\\\/Bilder', 'zwohue80g1a')\\n#11 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#12 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#13 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'downloadShare')\\n#14 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/public\\\/appframework\\\/app.php(134): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#15 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/core\\\/routes.php(124): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#16 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#17 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(Closure), Array)\\n#18 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/s\\\/Z39mIaB5HT76...')\\n#19 \\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/index.php(39): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/mnt\\\/weba\\\/b2\\\/60\\\/51382360\\\/htdocs\\\/mycloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"2016-01-27T18:04:49+01:00","method":"GET","url":"\/www.kneisle.de\/mycloud\/index.php\/s\/Z39mIaB5HT76630\/download?path=%2FBilder&files=0_quisma_Mazda_CX5_mobile_154x154%5B1%5D.gif&downloadStartSecret=zwohue80g1a"}
{"reqId":"Vqj4ssCoKK8AAEOMaXEAAADW","remoteAddr":"84.175.130.199","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2016-01-27T18:04:52+01:00","method":"GET","url":"\/www.kneisle.de\/mycloud\/index.php\/apps\/gallery\/config?extramediatypes=1"}```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
You didn't update your instance correctly
https://github.com/owncloud/activity/issues/419#issuecomment-149830559

---

You didn't delete the old files and just uploaded the new files into the existing folder.

https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#manual-upgrade-procedure

**Comment by RalfWW** [comment]
Yes, you right.
Thanks for your help!
