### ISSUE TITLE
owncloud activity notification, information leak

### ISSUE THREAD

**Issue by casper000** [owncloud/activity#457]
helow,

Is it possible to add in owncloud activity email report to send full list of activity of hour, day or week. In official documentation is written that not to loose data we must create accout to hold all shares for users. that account receives email notification for all activities in share but is not complete list. so if user deletes something it will be in that account's recycle bin folder. when user will report that file is lost it may be deleted by user. to identify problems like that it will be very easy if we will have complete actions of users. also we can find it in activities from web interface and activities can be found by others also but, oc lists few of them not all and I don't have error in oc log. so I am filtering it with mysql queries becouse oc web interface activities show max 10 activities latest. per day I have thousands of activities.

thank you

**Comment by nickvergessen** [comment]
Each account will only be notified about files he/she had access to. This can and will not be changed...

**Comment by casper000** [comment]
ok but sheres are in folder of user who has shared files to others am i right? that's the account owncloud suggest to create and share files to others because if user is deleted data will be deletes as well. so that user hold all shares an THAT USER RECEIVES ACTIVITIES BY OTHER MADE IN OWN SHARE BUT THEY ARE SEVERAL AND CHANGES ARE THOUSANDS. that's all.
