### ISSUE TITLE
Instant Notifications

### ISSUE THREAD

**Issue by markymif** [owncloud/activity#458]
Is it possible to have OwnCloud send a notification for each new batch of activity?  When I operate a shared folder on Dropbox, I get emails to say who added what etc.  But the best I can get is the setting or Hourly which sometimes ends up being two hours with OC.

**Comment by nickvergessen** [comment]
The activity app is not ment to be a instant notification thing. The problem e.g. is if you use the files_texteditor, the file is saved multiple times per minute. It would trigger an email each time... and also it is (depending on the instance size) quite expensive to get all users to notify etc. so this is delayed like it is now.

If you want to get the email each time one is assembled, the fastest you can running the following query:
```sql
UPDATE `oc_preferences` SET `configvalue` = 1 WHERE `configkey` = 'notify_setting_batchtime' AND `appid` = 'activity' AND `userid` = '<<<your user name>>>'
```

**Comment by markymif** [comment]
Thanks for that, I seem to be getting notifications every 30mins now which is better but still too long a delay.

**Comment by nickvergessen** [comment]
Right, then you need to switch to system cron and call it every minute, or you trigger the web UI every second.
That gets it to 15 minutes. If that is still too slow, you need to change https://github.com/owncloud/activity/blob/master/lib/backgroundjob/emailnotification.php#L63-L64 to 1 minute.

**Comment by markymif** [comment]
thanks, I have made your suggested changes and now it send out the alerts more prompt.

thanks again

**Comment by Aka4Code** [comment]
@nickvergessen Would be nice if this could be in configuration.
