### ISSUE TITLE
File List cropped in IE

### ISSUE THREAD

**Issue by markymif** [owncloud/activity#459]
Hi, just noticed this so unsure if its new to 8.2.2.

if I upload 16 folders in chrome, then look at the same folder content in IE11 all I see is 13 folders.  There is no scroll bar to look down further than the 13 folders.

If I then add some additional files to the root folder, they are there in Chrome, but not in IE11

**Comment by nickvergessen** [comment]
Please report in core: https://github.com/owncloud/core/issues using the issue template that contains some questions which help developers to reproduce your issue:
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version
