### ISSUE TITLE
Server time incorrect in client tab

### ISSUE THREAD

**Issue by teejcee** [owncloud/activity#472]
It appears that the time reflected in the Server Activity tab is GMT.

I'm in Sydney, Australia & some activity recently ( 02/03/16 ) was being reported as "11 hour(s) ago on ip-address" while the time in the Sync Protocol tab giave the correct local time & correct date. "2/03/16 12:10:10 PM"

I was requested by a moderator on the owncloud forum to change my system time to gmt
run a test & report here if it is still a problem.......it is.

I set time to gmt and made a change to my data. The Activity tab is definitely reporting gmt rather than system time.

For my change it showed "1 minute ago" while Sync tab showed system time. Which would be correct if I was actually in that zone.

Running server 8.2.2 with client 2.1.1 on linux mint 17.2 ( client & server )

**Comment by nickvergessen** [comment]
That is more of a client issue, but I just tested it and can reproduce with 2.1.1 but not on the latest 2.1 branch.
So I expect that the next update will fix this,
Ref https://github.com/owncloud/client/issues/4521
