### ISSUE TITLE
Remove left margin from files tabview

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/activity#475]
Left margin causes inconsistency of different tabs in the files sidebar:

The activity tab _with_ margin:
![bildschirmfoto von 2016-03-10 08-58-53](https://cloud.githubusercontent.com/assets/1374172/13663012/de57c3b2-e69e-11e5-8e37-248ad84d2350.png)
Other tabs don't have it:
![bildschirmfoto von 2016-03-10 08-59-04](https://cloud.githubusercontent.com/assets/1374172/13663013/e1e454e6-e69e-11e5-8d91-107f78af7f98.png)

@nickvergessen @jancborchardt is that intended?

**Comment by nickvergessen** [comment]
Well the problem is, if you modify/add/delete/share the file, we have the icon.
basically comment activities miss an icon, that is why they look "too far intended".

@jancborchardt can you craft an icon please?

**Comment by jancborchardt** [comment]
There already is an icon: `icon-comment`. I wouldn’t add it while the tab is separate though since it will just result in repeated icons.

So we should wait for the Activity tab being combined in core.

**Comment by nickvergessen** [comment]
The change and share icon can repeat too...

**Comment by jancborchardt** [comment]
I know. But the comment icon will definitely be the _only_ icon in the comments tab. So it does not make any sense to use it, cause it doesn’t help to distinguish anything – it’s just visual noise.

**Comment by nickvergessen** [comment]
We are talking abou tthe activity app and stream, which would be good to have an icon for.
I will test `icon-comment`

**Comment by jancborchardt** [comment]
Right, true. Misunderstanding since the original issie was about the margin. Yes, definitely goos to add the icon-comment when it's a mixed actions list.
