### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by dragotin** [owncloud/activity#477]
On a german installation the removal of a share is reported as 
![activity2](https://cloud.githubusercontent.com/assets/1070214/13669866/a434cb26-e6c6-11e5-836c-c22941a9b7bd.png)

In the web interface in English, the text is correct. I know we translate in transifex and can not influence and yadda, but ... it is a bit suspicious that in the german translation only the last word misses. 

Feel free to close if you are sure that this is just a translation issue.

**Comment by dragotin** [comment]
Ah, I should mention that *Sie  haben die Freigabe von fw für Bilder/kids* lacks a *"entfernt"*

**Comment by nickvergessen** [comment]
Will fix the translations, seems like they are not translated at all atm

**Comment by dragotin** [comment]
Hmm, I could not find the string ".... removed the share from..." in the English strings. Was wondering about that, but did not dig deeper tbh.

**Comment by nickvergessen** [comment]
Fixed them, should be updated in master tomorrow, I will put them on my "backport translations for 9.0.1" list

**Comment by danimo** [comment]
Wait did we also fix the "Du/Sie" mismatch there?

**Comment by nickvergessen** [comment]
yes
