### ISSUE TITLE
Log remote IP address with public link downloaded activity

### ISSUE THREAD

**Issue by mstrent** [owncloud/activity#479]
I know this info would be in the server logs, but it would be great if the Activity function also showed the IP address of remote users who download files via public links.

Our scenario is this: we deliver Public Disclosure Requests in installments to requestors via Owncloud public links. If a requestor doesn't access the first installment within a certain time period, we are allowed by law to consider the request inactive and discontinue work on creating/providing more installments. Seeing that the file was downloaded by a particular IP address at a certain time would give us a more definite "paper trail" when requestors download a PDR results installment.

Thanks for all you do. We love Owncloud!

**Comment by nickvergessen** [comment]
https://github.com/owncloud/activity/issues/350 duplicate
