### ISSUE TITLE
infinite scrolldown in OC9

### ISSUE THREAD

**Issue by Loki3000** [owncloud/activity#483]
While scroll down an activity app first page appears again.
In firebug console requests:
```
GET https://domain/index.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
GET https://domain/index.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
GET https://domain/index.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
GET https://domain/index.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
```
(since var not changes)

FF45

**Comment by nickvergessen** [comment]
Can you check the response of those requests? are they valid? what does the resonse look like?

**Comment by nickvergessen** [comment]
Also, anything in your owncloud.log?

**Comment by Loki3000** [comment]
Yes, responses valid and returns json for the first page (it's only 15 events at all now).
In server error log all clear.

**Comment by nickvergessen** [comment]
Can you check the headers of the response?
Something like:
```
X-Activity-First-Known: 6
X-Activity-Last-Given: 2
```
should be set.

**Comment by Loki3000** [comment]
```
x-activity-first-known	: 30
x-activity-last-given: 1
```

**Comment by nickvergessen** [comment]
Are the headers really lowercase for you?
Are you behind a proxy or something like that?

**Comment by nickvergessen** [comment]
If so, please try https://github.com/owncloud/activity/pull/488

**Comment by Loki3000** [comment]
Yes. Headers looks exactly as I paste above.
I have tested with proxy and without.
With a fix all works well. Thanks!
