### ISSUE TITLE
Activities not loading (Autoload path not allowed)

### ISSUE THREAD

**Issue by Adesso** [owncloud/activity#491]
**OS** CentOS 7 64 bit
**DB** mysql  Ver 14.14 Distrib 5.6.29
**Webserver** nginx 1.6.3
**PHP**  5.6.19
**Ownloud** 9.0.0
**Plugin** Activity  2.2.1
After a Manual upgrade from OC 8.2.2 to 9.0.0 the Activity pane on all Folders no longer loads. The log error:
{"reqId":"xxx","remoteAddr":"xxx","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Mess                                                                                age\":\"Autoload path not allowed: \\\/var\\\/www\\\/xxx\\\/cloud\\\/apps\\\/files_sharing\\\/lib\\\/activity.php\

- I have tried to disable re-enable the app
- Clear the jobs table with DELETE from oc_jobs WHERE `class` LIKE '%CommandJob%' AND `argument` LIKE 'O:33%Files_Versions%'

When I try to view the apps/activity I get the same error, and no results on the page.

Only current solution is to disable the the Activities. 
--more info on request.--

**Comment by nickvergessen** [comment]
Do you have the files_sharing app enabled? Because that is what is failing to load.

**Comment by Adesso** [comment]
As far as I can see this is a standard app that comes with OC 9, and there is no way to disable this in the admin backend. I could remove the app files, but this would render OC a bit useless... anyway

I have disabled all apps but the Activity App to test some more. 
**Results. **
Create a new folder temp - Worked, showed that I created it 
View old standard Folder **Documents **- No result, but also no Log error.... The little wheel just keeps turning ;) 

I can only assume the old Activities can't be loaded for some reason. I haven't debugged it further...

**Comment by nickvergessen** [comment]
Can you please run the command `./occ app:list` from your ownCloud root?

**Comment by Adesso** [comment]
Enabled:
  - activity: 2.2.1
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
Disabled:
  - comments
  - encryption
  - external
  - federation
  - files_external
  - files_mv
  - files_pdfviewer
  - files_sharing
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - notifications
  - provisioning_api
  - systemtags
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap

**Comment by nickvergessen** [comment]
Right, now I saw the issue, try https://github.com/owncloud/core/pull/23461
