### ISSUE TITLE
Activity API and improvements

### ISSUE THREAD

**Issue by karlitschek** [owncloud/activity#494]
# ActivityStream and ActivityPub 

## Precondition
This feature will be added to the current activity app. 

## Requirements
Any client should be capably to query the server for activities. We will support Activity Streams https://www.w3.org/TR/activitystreams-core/ and ActivityPub https://www.w3.org/TR/2016/WD-activitypub-20160128/ .

## Feature description
2. How to map our activity strings into this
![1](https://cloud.githubusercontent.com/assets/867445/14020631/5ef489dc-f1ae-11e5-8d04-da99bcf768f4.jpg)

Basically we have localized actions with parameters and the parameters can be links. We will have a HTML free “name” on the activities and a HTML containing “summary”. The desktop client can then implement his own rendering if he knows the type, and can fall back to the HTML free version when the activity is unknown, while in the UI we can still use HTML like before.

Also the API docs should clearly state which HTML or pseudo-HTML is allowed or if only real HTML is to be used.

Php API
The php Api needs a bit of adjustment at the same time. It is required to reflect the changes on the output as per above. Matching activity and object types of actions, providing additional info where ever possible, etc. have to be enforced.
At the same time we should split the current OCP\Activity\IExtension and IManager interfaces into the jobs they actually implements:
1. Displaying/rendering/preparing of activities
2. Filters for the left-side bar of the activity app
3. Settings which type of activities should be displayed/emailed/…

## Combined sidebar time line 

Problem

At the moment the sidebar for a file has separate tabs for the chronological lists of »Activity«, »Comments« and »Versions«. This makes it very cumbersome to interact with each of these functions.

For example, comments are displayed in the Activity list but not possible to interact with. Or changes are also displayed in the Activity list but not possible to restore as they are basically versions.

Design

The new »Activity« tab merges activities, comments and versions into a single timeline stream. This way all chronological info is in one place and can be interacted with in a very simple way.

![2](https://cloud.githubusercontent.com/assets/867445/14020677/95c2b696-f1ae-11e5-9d70-8564d34f74f9.jpg)

## Open Questions
1 activity per user has issues
One action results in 1 activity per user, therefor commenting activities (like in social media) makes no sense, because each user can/would only see his own comments.
A potential solution would be to split activities basically into 2 things (2 db tables):
1. the action (1 for all): activity id, user, time, object type+id, app, type
2. the mapping (1 per user): parameters, user-based information
Then comments would be done against the action and not the mapping and things like “commenting activities” makes somewhat more sense.
Php API would need adjustment to reflect this as well. Either when creating an action either the user list is also given, of you can later add mapping entries for a given action.

**Comment by karlitschek** [comment]
additional context. https://github.com/owncloud/activity/issues/405
Please not that this is the main ticket

**Comment by nickvergessen** [comment]
> Combined sidebar time line

Uhh, where does this come from all of a sudden, that is a completly different task?!

**Comment by MTRichards** [comment]
Integration of data from different sources need some form of consistent data structure.
For web view in 9.1, comments go into the activity stream.
This needs a new system for placing comments into the activity stream.
Need to update the "don't notify me about my own actions" to now not include non-file operations, such as comments.
Activity stream has a filter for all, comments, and activity.

There is likely a new table to make this happen, or a migration of the existing table.
We start this with 9.1 for local activities and comments, and start there.

**Comment by MTRichards** [comment]
Estimation: 2.5 weeks

@jancborchardt

**Comment by nickvergessen** [comment]
* Combining with comments has been moved to https://github.com/owncloud/activity/issues/504
* The W3C stuff is already discussed in https://github.com/owncloud/activity/issues/405

So I'm closing this epic

**Comment by xoroz** [comment]
hello everyone, I am trying to list all downloaded files activity for one day.
I tried searching the apache log file but I am unable to get the file name.
occ does not seem to provide that either, can someone help me?
