### ISSUE TITLE
Activities Take 30 Minutes to Load, and oc_activities Table is Very Large

### ISSUE THREAD

**Issue by alpha-ray-burst** [owncloud/activity#495]
I have searched the open and closed issues, but did not see my exact issue. I also have consulted the ownCloud community but we were unable to resolve this issue. 

My thread on the ownCloud forums:
https://forum.owncloud.org/viewtopic.php?t=33097

Description of issue: 

When I select a folder or file, the activities panel opens to the right with a spinning wheel. The wheel spins for about 30 minutes before showing the relevant activities. In the Activity app, the initial page with the most recent activities loads instantly, but when I scroll down to reveal more activities, it takes about 30 minutes for the spinning wheel to go away and display more activities.

Upon looking into this issue, I noticed that the oc_activities table was very large. It was about 70GB when I first noticed, and grew to 95GB within about two weeks. At the end of the two weeks, I enabled "activity_expire_days" (14) in my config.php file, which stopped the table from growing, but did not fix the 30-minute load times.

Below is the information requested in the "posting a new issue guidelines."

### Steps to reproduce
1. Install ownCloud 8.2.1 on a dedicated Linux Ubuntu 14.03 LTS Server. (Dell PowerEdge 530)
2. Use REDIS memcaching
3. Use Encryption app
4. Create a 15TB (3TB x 6 in Raid-5) storage volume to hold ownCloud's data folder and mount to /mnt
5. Sync 2TB of files (roughly 100,000 files) from Box.com, using box sync app and ownCloud sync app pointed at same folder.
6. Let the sync apps sync in real time for roughly one month.
7. Stop using sync apps
8. Select any file or folder, which will open the activity panel on the right hand side of your screen.

### Expected behaviour

Recent activities should load in the activity panel quickly.

### Actual behaviour

Loading wheel spins for about 20-30 minutes before displaying recent activities.

### Server configuration

**Operating system**: 

Linux Ubuntu 14.03 LTS

**Web server:** 

Apache 2

**Database:** 

MySQL 

**PHP version:** 

5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)

8.2.1

**Updated from an older ownCloud or fresh install:**

fresh install

**Where did you install ownCloud from:**

direct from owncloud.org (downloaded with wget)

**Signing status (ownCloud 9.0 and above):**

N/A

**List of activated apps:**

Activity 2.1.3
Default encryption module 1.1.0
Deleted files 0.7.0
First Run Wizard 1.1
Gallery 14.2.0
Mail Template Editor 0.1
Notifications 0.1.0
PDF Viewer 0.7
Provisioning API 0.3.0
Share Files 0.7.0
Text Editor 2.0
Updater 0.6
Versions 1.1.0
Video Viewer 0.1.3
[EXPERIMENTAL] Password Policy 1.1

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocefn2u03m3v",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/mnt\/data",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "logfile": "\/var\/log\/owncloudAttack.log",
        "loglevel": 0,
        "log_authfailip": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "alerts",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "activity_expire_days": 14
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

not using

**Are you using encryption:** yes/no

yes, via the encryption app

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Yes, I have used Webdav to mount ownCloud as a network drive in Windows and OS X, as well as using the ownCloud sync app extensively.

### Client configuration
**Browser:**

Chrome 49.0.2623.87 (64-bit)

(Results are the same in all browsers, with no errors shown in developer console)

**Operating system:**

Mac OS X 10.8.5

(Results are the same in Windows 7, 8, 10, and OS X El Capitan)

#### Web server error log

Will add later if needed. Please advise.

#### ownCloud log (data/owncloud.log)

Will add later if needed. Please advise.

#### Browser log

Will add later if needed. Please advise.

If there is any more information I can provide to help resolve this issue, please let me know.

Thank you.

**Comment by apg1980** [comment]
i have exactly the same issue. [https://github.com/owncloud/activity/issues/481](url)
i tryed to cleare my activity tables but the issue still exists.

**Comment by nickvergessen** [comment]
95GB of activities sound like a hole new and other issue.

I just saw that we have no index for the sidebar query. Are you advanced enough to add one index over the object_type and object_id columns? And see if that helps?

**Comment by alpha-ray-burst** [comment]
Thanks for the reply, nickvergessen.

I'm sorry, but no, I do not know how to add indexes over columns. 

If you could explain how to do this, and if the scope of risk of adding the indexes does not extend past the activities app (i.e. I'm not going to crash ownCloud by doing this), then I would be happy to try it out.

**Comment by nickvergessen** [comment]
This query should work for mysql

```sql
ALTER TABLE `oc_activity` ADD INDEX `activity_object` (`object_type`, `object_id`)
```

**Comment by alpha-ray-burst** [comment]
Ok, I had a problem creating the index and would like to ask your advice.

The first time, I ran the query via SSH and it gave me an error after about 10 minutes. Something to the effect of "lost connection to SQL database."

Then I tried to run the query directly on the server's CLI, and got the following error:
"ERROR 1061 (42000): Duplicate key name 'activity_object' "

I assumed this was because I ran the query twice, and I considered just deleting "activity_object," but I didn't know if this would break anything... and I also was not sure if my SQL would work.

Should I just run the following command and then retry adding the index?

``DROP INDEX `activity_object` ON `oc_activity`; ``

**Comment by nickvergessen** [comment]
Looks good

**Comment by alpha-ray-burst** [comment]
nickvergessen,

You have performed a miracle! The issue is fixed.

I ran the SQL query you provided on my database as instructed:

``ALTER TABLE `oc_activity` ADD INDEX `activity_object` (`object_type`, `object_id`)``

It returned this:

`` Query OK, 0 rows affected (31 min 37.14 sec)
Records: 0 Duplicates: 0 Warnings: 0 ``

And then I went back to ownCloud, enabled the Activity app (I had it disables since it was broken), and now when I select folders and files, the activity in the details panel loads instantly!

Thank you so much for helping me!

**Comment by nickvergessen** [comment]
Sounds good,

@DeepDiver1975 I think we have to add that index, but might be slow for huge instances...
Any recommendation?

**Comment by alpha-ray-burst** [comment]
Hey guys, I just noticed that the infinite scroll in the Activity app itself is still not fixed. It hangs on loading the second page. I don't suppose there's another index I can add to magically fix this, is there?

**Comment by nickvergessen** [comment]
Can you create a new issue and supply all the information from the issue template:
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by 3dmedium** [comment]
I just saw the Issue of @adamk-skyrocket at a complete Updated OwnCloud Installation:
ownCloud	10.2.0 (stable)

In the Database there is the following Line:
Table: oc_activity
subject:  shared_group_self
subjectparams:    [{"objectid":"filename"}, "group name"]

if the group with "group name" was deleted the activity app loads data "forever" while comming to this entry. (Loading Data stops with exception)
In the owncloud log there is an entry with an exception as mentioned by @adamk-skyrocket 
"Message":"Call to a member function getDisplayName() on null"

When one deletes the line in the mysql table then activity app loads data again.
