### ISSUE TITLE
Add ability to filter by last hour, day, week, month or year in the Web GUI

### ISSUE THREAD

**Issue by oparoz** [owncloud/activity#496]
The web GUI retrieves all activities and offers to filter by category. It would be nice if we could apply an extra time filter to those listings.

Proposed so far:

* last hour
* last 24h
* last 7 x 24h
* last 30 x 24h
* last 365 x 24h

This would all be done in Javascript, using the data returned by the API.

One caveat is that this could represent a massive amount of data depending on the user's activity.

@nickvergessen @jancborchardt

**Comment by jancborchardt** [comment]
Why do we need that filter though exactly? It’s already sorted chronologically, so that filter is inherent. Just stop scrolling. ;)

**Comment by nickvergessen** [comment]
Yeah, also "last 365 x 24h" might be useless, when the admin prunes after 30days e.g.
