### ISSUE TITLE
Activity APP spams Log with "Session closed" messages, when Mail App is activated

### ISSUE THREAD

**Issue by Maulwurf16** [owncloud/activity#507]
See my Issue here: 

https://github.com/owncloud/mail/issues/1408

The Activity App spams the owncloud.log with the cron job intervall.

`Error while running background job (class: OCA\Activity\BackgroundJob\EmailNotification, arguments: ): {"Exception":"Exception","Message":"Session has been closed - no further changes to the session are allowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/session\/memory.php(49): OC\Session\Memory->validateSession()\n#1 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/tokenstorage\/sessionstorage.php(63): OC\Session\Memory->set('requesttoken', 'O6BErTBPZ4K\/qar...')\n#2 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/csrftokenmanager.php(57): OC\Security\CSRF\TokenStorage\SessionStorage->setToken('O6BErTBPZ4K\/qar...')\n#3 \/var\/www\/owncloud\/lib\/public\/util.php(496): OC\Security\CSRF\CsrfTokenManager->getToken()\n#4 \/var\/www\/owncloud\/lib\/private\/template.php(75): OCP\Util::callRegister()\n#5 \/var\/www\/owncloud\/apps\/activity\/lib\/mailqueuehandler.php(250): OC_Template->__construct('activity', 'email.notificat...', '')\n#6 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(134): OCA\Activity\MailQueueHandler->sendEmailToUser('Maulwurf', 'markus.westerha...', 'de_DE', 'Europe\/Berlin', 1460286026)\n#7 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(94): OCA\Activity\BackgroundJob\EmailNotification->runStep(500, 1460286026)\n#8 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OCA\Activity\BackgroundJob\EmailNotification->run(NULL)\n#9 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/timedjob.php(53): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))\n#10 \/var\/www\/owncloud\/cron.php(141): OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))\n#11 {main}","File":"\/var\/www\/owncloud\/lib\/private\/session\/memory.php","Line":105}`

All settings, activated apps, etc are the same, as with the linked issue

**Comment by nickvergessen** [comment]
Please update to 9.0.1 https://github.com/owncloud/activity/pull/487
