### ISSUE TITLE
Activity app web feed not getting translated.

### ISSUE THREAD

**Issue by pedrohc** [owncloud/activity#526]
### Steps to reproduce
1. Change language to a non-default one.
2. Do some activities.
3. Go to the activity app tab
4. Activities subject should be partialy translated (except for tha actions).
### Expected behaviour

Everything should be translated. Already checked l10n strings and they are there, but for some reason the they're not getting to the web feed.
### Actual behaviour

The actions on the feed don't get translated, showing 'deleted' and 'created' instead of the language equivalent.
### Server configuration

**Operating system**:
Debian 8
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
9.0
**Where did you install ownCloud from:**
Tarball
**Signing status (ownCloud 9.0 and above):**

**Comment by DeepDiver1975** [comment]
> Change language to a non-default one.

Which language did you choose?

**Comment by DeepDiver1975** [comment]
> The actions on the feed don't get translated, showing 'deleted' and 'created' instead of the language equivalent.

mind posting a screenshot?

THX

**Comment by pedrohc** [comment]
I chose brazilian portuguese (pt_BR).

Here is the screen:
![activity_not_translated](https://cloud.githubusercontent.com/assets/4870520/16302043/3c8b147a-391f-11e6-85f5-bb0a0d95c3da.png)

**Comment by dragotin** [comment]
This works fine in 9.1:
![activities](https://cloud.githubusercontent.com/assets/1070214/16680650/778fa43c-44f0-11e6-83c8-976fa4a90b74.png)

Since this is not subject of backporting, we can consider this fixed. Thanks!

**Comment by DeepDiver1975** [comment]
We actually have a script to backport translations

**Comment by PVince81** [comment]
@DeepDiver1975 can you run it ?

**Comment by PVince81** [comment]
@DeepDiver1975 please run the translation backport script

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 please run the translation backport script

I tried many times - but I failed :cry:

**Comment by PVince81** [comment]
ok then let's not insist, closing, we have other stuff to do...

**Comment by PVince81** [comment]
please upgrade!
