### ISSUE TITLE
Upgrade settings panel to implement new ISettings interface

### ISSUE THREAD

**Issue by tomneedham** [owncloud/activity#554]
Upon the merge of https://github.com/owncloud/core/pull/26449 the settings panel registration will need to be upgraded to implement the new ISettings panel style, allowing the panel to register to a specific section if necessary.

- [x] kill https://github.com/owncloud/activity/blob/master/tests/AppInfo/AppTest.php#L44-L60

**Comment by PVince81** [comment]
any update?

**Comment by tomneedham** [comment]
closed with https://github.com/owncloud/activity/pull/561
