### ISSUE TITLE
Bug in translated activity (timestamp)

### ISSUE THREAD

**Issue by titoss** [owncloud/activity#560]
### Steps to reproduce
1. Log in on OwnCloud Web
2. Change default language on Serbian Latin (Exist two, Serbian (Cyrilic) and Serbian Latin)
3. Make some changes on files or folders (create, change, delete, share) 
4. Visit Activity page

### Expected behaviour
Show correct timestamp of changed files and folders.

### Actual behaviour
Instead that, time in activity shows on Chinese letters or something similar (for example strings like "Few Seconds Ago", "Day Before"...are shown like 小時前, instead of Serbian)

### Server configuration
Operating system: CentOS 6.8 final

**Web server:**Apache/2.2.15 

**Database:**MySQL

**PHP version:**5.6.24

**ownCloud version:** 9.1.3

**Where did you install ownCloud from:**Tarball

**Signing status (ownCloud 9.0 and above):**

**List of activated apps:**Native

**The content of config/config.php:**
'datadirectory' => '/data/',
  'overwrite.cli.url' => 'https://example.com',
  'dbtype' => 'mysql',
  'version' => '9.1.3.1',
  'dbname' => 'example',
  'dbhost' => 'x.x.x.x',
  'dbtableprefix' => 'occ_',
  'logtimezone' => 'Europe/Belgrade',
  'installed' => true,
  'theme' => 'userdefined',
  'loglevel' => 0,
  'maintenance' => false,
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'example.com',
  'forcessl' => true,

**Are you using external storage, if yes which one:** NFS

**Are you using encryption:**no

**Are you using an external user-backend, if yes which one:** no

### Example:

![ex](https://cloud.githubusercontent.com/assets/25642196/22747106/59a7ae76-ee26-11e6-9059-88c6f24ce2ed.png)

**Comment by DeepDiver1975** [comment]
> Example:
> 
> ex

this screenshot is taken from files - and this is where I can reproduce this.
Looks unrelated to activity ....

**Comment by DeepDiver1975** [comment]
Okay - moment.js only knows about 'sr' and 'sr-cyrl' - within owncloud we know 'sr@latin' and 'sr' - we need to adjust this properly. I'll take care ....

**Comment by DeepDiver1975** [comment]
@titoss here is the fix - https://github.com/owncloud/core/pull/27120

**Comment by titoss** [comment]
Thats correct, works. Many tnx DeepDiver :-)

**Comment by titoss** [comment]
I solved with this.
Just is needed to be changed in the file (bolded is correct): moment-with-locales.js
Line 8698:   var sr_cyrl = _moment__default.defineLocale('**sr**', {
Line 8795:   var sr = _moment__default.defineLocale('**sr@latin**' {
