### ISSUE TITLE
Activity icon is not shown

### ISSUE THREAD

**Issue by davitol** [owncloud/activity#563]
Activity icon is missed in oC master "version":"10.0.0.1","versionstring":"10.0.0","edition":"Community","productname":"ownCloud"

![screen shot 2017-03-08 at 15 58 56](https://cloud.githubusercontent.com/assets/10596560/23709008/442eeafc-0418-11e7-93e0-dfb6e8a1df90.png)

**Comment by DeepDiver1975** [comment]
@tomneedham wana have a look? THX

**Comment by tomneedham** [comment]
Fixed with #27413
