### ISSUE TITLE
Display group display name instead of group id when possible

### ISSUE THREAD

**Issue by PVince81** [owncloud/activity#575]
1. Enable the custom groups app: https://github.com/owncloud/customgroups
1. Create a custom group "Group One"
1. Share a folder "test" with "Group One"
1. Select the activity tab in the right sidebar for the folder "test"

Expected result: group name shows as "Group One"

Actual result: group name displays the internal id "customgroup_groupone"

@pmaier1 FYI

Fixing this should be a matter of an hour or two.

**Comment by PVince81** [comment]
since there is the possibility of duplicate group names, also have a tooltip with the actual group id

**Comment by pmaier1** [comment]
Yep, this definitely needs to be done for the next release of the activity app. @felixboehm

**Comment by PVince81** [comment]
@sharidas one for you. There is a new method `getDisplayName` on the `IGroup` interface that should be used.

**Comment by sharidas** [comment]
The changes are merged: https://github.com/owncloud/activity/pull/582
