### ISSUE TITLE
Estonian language translation error

### ISSUE THREAD

**Issue by martinlindjarv** [owncloud/activity#581]
On the opening page there is a sentence "ownCloud - veebitenused sinu kontrolli all".
There's a missing "e" and it should be "ownCloud - veebiteenused sinu kontrolli all"

**Comment by SamuAlfageme** [comment]
Hey @martinlindjarv! Translations are handled in https://www.transifex.com/owncloud-org/owncloud you can always join the translation team to help improve your language! ☺️

There you go the line it appears in for reference: https://github.com/owncloud/core/blob/master/lib/l10n/et_EE.js#L103 (find it after you join the translation team under ownCloud organization > Resources > core > Estonian: https://www.transifex.com/owncloud-org/owncloud/viewstrings/#et_EE/core) 

Thanks for reporting! Closing here as activity-unrelated. (The token comes from the core repository)
