### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by pmaier1** [owncloud/activity#591]
Please add a changelog to this repository logging changes version-wise as far as possible.

- [ ] Add CHANGELOG.md
- [ ] Stick to the keepachangelog structure proposed and implemented by @PVince81 in core and e.g. https://github.com/owncloud/customgroups/blob/master/CHANGELOG.md

There's a script to compile the changelog according to merged PRs. For apps it could also be easier to note down changes manually. For the future changelogs should be updated before the QA phase begins to make life for QA easier knowing exactly what to test.

Thanks a lot!

@PVince81

**Comment by PVince81** [comment]
Changelog added here https://github.com/owncloud/activity/pull/589
