### ISSUE TITLE
Activity TestPlan Results

### ISSUE THREAD

**Issue by davitol** [owncloud/activity#592]
## 'Activity' Test Plan

- Run Testplan with all checked notifications in Activity settings menu and a mail set in our oC server.

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable Activity app via CLI using ```occ app:enable activity``` | The apps gets enabled | ✅   |
Disable Guest app via CLI using ```occ app:disable activity``` | The apps gets disabled |  ✅   |
**All activities section** |  |   |
|  |   |
Check that all activities done in this Testplan are shown in this section |  |  ✅   |
**Activities by you section** |  |   |
|  |   |
Check that all activities done with my user in this Testplan are shown in this section |  |  ✅  |
**Activities by others section** |  |   |
Check that all activities done dealing with my user by other users in this Testplan are shown in this section |  |  ❌    | https://github.com/owncloud/activity/issues/596
An LDAP user shares a file with my user | Check that LDAP username is shown properly in this section | ✅ |
An LDAP user edits a file shared with my user | Check that LDAP username is shown properly in this section |  ✅   |
A Shibboleth user shares a file with my user | Check that Shibboleth username is shown properly in this section | ✅   |
A Shibboleth user edits a file shared with my user | Check that Shibboleth username is shown properly in this section | ✅   |
**Favorites section**|  |   |
|  |   |
Make favorite a file | Check that the notification is shown in activity section and in the sidebar | ✅   |
Make favorite a folder | Check that the notification is shown in activity section and in the sidebar | ❌   | https://github.com/owncloud/activity/issues/593  https://github.com/owncloud/activity/issues/594
**Comments**|  |   |
|  |   |
Make a comment in a file | Check that the notification is shown in activity section and in the sidebar | ✅   |
Make a comment in a folder | Check that the notification is shown in activity section and in the sidebar | ✅ |
**Shares section**|  |   |
|  |   |
Share a file/folder | Check that the notification is shown in activity section and in the sidebar| ✅   |
Share a file/folder with a user of other oC server | Check that the notification is shown in activity section and in the sidebar| ✅   |
Share a file/folder via link | Check that the notification is shown in activity section and in the sidebar| ✅   |
Receive a share for another user| Check that the notification is shown in activity section and in the sidebar| ✅  |
Receive a share for another user of other oC server| Check that the notification is shown in activity section and in the sidebar| ✅   |
Receive a file/folder via link adding to your owncloud| Check that the notification is shown in activity section and in the sidebar| ✅  |
**Settings section stream**|  |   |
|  |   |
Uncheck a new file or folder has been created stream notification and create a folder| Notification is not shown | ✅   |
Uncheck a file or folder has been changed stream notification and change a file| Notification is not shown | ✅  |
Uncheck limit notifications about creation and changes to your favorite files stream  notification and change favorite file and a regular file| Notification is not shown | ✅  |

**Comment by davitol** [comment]
**Known issues**

**Comment by felixboehm** [comment]
assume finished... ?

**Comment by davitol** [comment]
> assume finished... ?

No, there are pending scenarios not tested yet in the Test Plan (marked as 🚧 ) I will finish this test cases today

**Comment by davitol** [comment]
@felixboehm Testplan completed. :shipit:
