### ISSUE TITLE
Favorite folder activity is not shown in Activity section

### ISSUE THREAD

**Issue by davitol** [owncloud/activity#593]
Using Activity version 2.3.4 and oC stable10:

![folderfav](https://user-images.githubusercontent.com/10596560/30101799-eee01d40-92ed-11e7-9dec-e41091fe8d8c.gif)

**Comment by pmaier1** [comment]
Hmm, not sure if adding a favorite needs to show up as an activity. I would expect to see actions in favorite folders there. TBD for next version.

**Comment by davitol** [comment]
@pmaier1 Understood, thanks for the clarification

> I would expect to see actions in favorite folders there

That's what happens so let's close the ticket
