### ISSUE TITLE
Skeleton files are shown as favorites in activity section

### ISSUE THREAD

**Issue by davitol** [owncloud/activity#594]
oC stable10 and activity app version 2.3.4

![screen shot 2017-09-06 at 12 08 55](https://user-images.githubusercontent.com/10596560/30106669-7fc8657a-92fc-11e7-9e36-f78f5ff7ede1.png)

**Comment by pmaier1** [comment]
Not that much of an issue. For some it might even be nice as the activity stream is not empty when logging in to a new account. Closing.
