### ISSUE TITLE
Activity not reporting unshare actions done by the receiver of a share

### ISSUE THREAD

**Issue by pako81** [owncloud/activity#615]
In 10.0.7 unshare actions done by the receiver of a share are now properly logged. However, it looks like that no entry is generated in the `oc_activity` table for such actions.

Since the admin_audit app correctly logs this means the hook is working correctly. Activity might just need to adjust listening to the hook. 

@PVince81 as discussed.

**Comment by PVince81** [comment]
considering that the hook did not exist before, the activity app could not have this feature so it's an enhancement

**Comment by cdamken** [comment]
@pmaier1 @hodyroff FYI

**Comment by hodyroff** [comment]
Agree it is an enhancement, as we put it in the audit log, we should also show it in the activity for the sharee.

Should we also show it in the activity of the owner and the sharer?!

**Comment by thommierother** [comment]
Changes in the sharing status should be visible for the sender AND the receiver of the share. For the receiver just as an activity log, for the sender just as a reminder that the receiver will no longer receive information inside this share
