### ISSUE TITLE
Error loading activities

### ISSUE THREAD

**Issue by sfmarques** [owncloud/activity#617]
I get this error when clicking in Activities or in the file. 

Docker ownCloud 10.0.7.2

![screenshot from 2018-04-18 18-23-28](https://user-images.githubusercontent.com/5604227/38947758-a7224a84-4335-11e8-9aa4-502901a81b5f.png)

Thanks

**Comment by DeepDiver1975** [comment]
anything in the server log?
anything in the browser console?

**Comment by sfmarques** [comment]
server log (everything) is fine and browser console:
![image](https://user-images.githubusercontent.com/5604227/39004112-5fe81148-43f4-11e8-813f-0022669daada.png)

**Comment by DeepDiver1975** [comment]
can you take a screenshot of the network tab please?

**Comment by sfmarques** [comment]
Network tab?

**Comment by DeepDiver1975** [comment]
the network tab is part of the browser tools/console

see https://developers.google.com/web/tools/chrome-devtools/network-performance/

**Comment by sfmarques** [comment]
![image](https://user-images.githubusercontent.com/5604227/39041064-19a40228-4480-11e8-9d3f-ec55c7243c89.png)

**Comment by DeepDiver1975** [comment]
Please increase the log level to debug and have another look in the owncloud server log.

https://doc.owncloud.org/server/latest/admin_manual/configuration/server/config_sample_php_parameters.html?highlight=loglevel#logging

**Comment by sfmarques** [comment]
Sorry, i cant because its a docker image and changing to 4 crashes the container :(

**Comment by sfmarques** [comment]
Ignore last post, changed but server log is he same

**Comment by davitol** [comment]
Activity seems to work fine. No other people was able to reproduce this issue, so probably it was a server configuration issue not related to ownCloud. Let's close the ticket
