### ISSUE TITLE
[For 10.0.9] Activity 2.3.7 release

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/activity#621]
# App release template

When marking a task as done, please add your name to the task!

### Reason
- Release needed for
   - [x] #620 
   - [x] https://github.com/owncloud/enterprise/issues/2510

### QA
- [x] Create release branch https://github.com/owncloud/activity/tree/release-2.3.7 @davitol
- [x] Create "$version Testplan"## 'Activity' Test Plan https://github.com/owncloud/activity/issues/629 @davitol
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol

Results for Release branch https://github.com/owncloud/activity/tree/release-2.3.7

- Run Testplan with all checked notifications in Activity settings menu and a mail set in our oC server.

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Changes in the docs needed?

### Build & Marketplace release

- [x] Bump version in info.xml @patrickjahns
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' @patrickjahns
- [x] Create github tag for '$version' @patrickjahns
- [x] Build and sign tarball from github tag '$version' @patrickjahns
- [x] Upload to marketplace @patrickjahns
- [x] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns
- [x] Rename QA milestone to '$version' @patrickjahns
- [ ] Add a new 'Unreleased' section in CHANGELOG.md @patrickjahns #636
- [x] Create PR to merge changes back to `master` @patrickjahns

**Comment by pmaier1** [comment]
Check to wait for another bugfix https://github.com/owncloud/enterprise/issues/2510

**Comment by PVince81** [comment]
@patrickjahns https://github.com/owncloud/activity/pull/626 is merged already so we can include it. I'll add a test plan there to save some time.

**Comment by PVince81** [comment]
changing version from 2.4.0 -> 2.3.7 as we only have minor changes / fixes

the only addition is the HTML template for activities, but one could argue that it's tech debt and it got missed when implementing mails in the first place

**Comment by PVince81** [comment]
PR for changelog and version increase: https://github.com/owncloud/activity/pull/628
