### ISSUE TITLE
Jquery 2 Migration

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/activity#637]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9

See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.click()`

- [x] js/script.js
- [x] js/settings.js

## Neglectable

`.ajax()`

- [x] js/script.js

`.data()`

- [x] js/activitytabview.js
- [x] js/script.js

not affected by changes.
however here's a PR to get rid of these later: https://github.com/owncloud/activity/pull/571

`.attr()`

- [x] js/script.js
- [x] js/settings.js

`.prop()`

- [x] js/settings.js

`.before()`

- [x] js/activitytabview.js

**Comment by PVince81** [comment]
PR here for the click adjustment: https://github.com/owncloud/activity/pull/638

**Comment by PVince81** [comment]
I have verified that the activity app still works **without** modifications in regards to pagination and the affected methods above.

This means that we don't need to schedule a release for the click adjustment https://github.com/owncloud/activity/pull/638 and can just let it be bundled in whatever future release will come.

Let's close this ticket once the PR is merged.
