### ISSUE TITLE
jquery-ui-migration

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/activity#643]
# jQuery UI Upgrade

See the full [upgrade 1.11. guide](https://jqueryui.com/upgrade-guide/1.11/)

See the full [upgrade 1.12. guide](https://jqueryui.com/upgrade-guide/1.12/)

## [1.12] (tooltip) CSS class changes

`.tooltip()`

- [x] /js/activitytabview.js
- [x] /js/script.js

**Comment by PVince81** [comment]
date tooltip still works
