### ISSUE TITLE
Activity 2.4.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/activity#653]
### Reason
- For the new semver logic, we need the minor version component to update to ensure all past migrations run. (there were some introduced over patch version update)
- [x] Fix for other missing migrations: https://github.com/owncloud/activity/issues/652

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "2.4.0 Testplan" @davitol  https://github.com/owncloud/activity/issues/656
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create github tag for 'v$version'
- [x] Build and sign tarball from github tag 'v$version'
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch

**Comment by davitol** [comment]
QA-ready, no blocker issues found. Results here:  https://github.com/owncloud/activity/issues/656

- [ ] We have to modify changelog file and add at the end ```[2.4.0]: https://github.com/owncloud/activity/compare/v2.4.0...v2.3.8```
