### ISSUE TITLE
[For 10.1] Activity 2.4.2

### ISSUE THREAD

**Issue by PVince81** [owncloud/activity#678]
### Reason
- [x] Fix for federated user id in activities: https://github.com/owncloud/activity/pull/672

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Test "$2.4.2 Activity" app @davitol 
- [x] Test Changelog item: https://github.com/owncloud/activity/pull/672 @davitol 

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` and upload as Github release => https://github.com/owncloud/activity/releases/tag/v2.4.2RC2
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist` and upload as Github release
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch

### Specifics

- Open tickets before QA can start
- Other specifics for app release

**Comment by PVince81** [comment]
cannot build RC1 and I've already tagged too early: https://github.com/owncloud/activity/issues/700

**Comment by PVince81** [comment]
2.4.2RC2 ready for testing: https://github.com/owncloud/activity/releases/tag/v2.4.2RC2

@davitol

**Comment by davitol** [comment]
@PVince81 Tarball is QA-Ready
