### ISSUE TITLE
Activity 2.5.0

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/activity#739]
### Reason

- Release needed for https://github.com/owncloud/activity/pull/738

Note: version will be set to 2.5.0 as we bump the min version and have a min-requirement for 10.2 in info.xml currently

### QA

- [x] Create **QA Milestone** @patrickjahns 
- [x] Move items from `development` to `qa` @patrickjahns 
- [x] Create release branch with the format "release-$version" @patrickjahns 
- [x] Create "2.5.0 Testplan" @davitol https://github.com/owncloud/activity/issues/742

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix) @patrickjahns 
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown) @patrickjahns 

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch @patrickjahns 
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build) @patrickjahns 
- [x] Upload as Github release using changelog entries @patrickjahns 
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch @patrickjahns 
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build) @patrickjahns 
- [x] Upload as Github release using changelog entries @patrickjahns 
- [x] Smoke test tarball (at least install + enable) @patrickjahns 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details) @patrickjahns 
- [x] Publish tarball for customers (see handbook for details) @patrickjahns 
- [x] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns 

### Post-release

- [x] Rename QA milestone to '$version' @patrickjahns 
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01) @patrickjahns 
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number @patrickjahns

**Comment by davitol** [comment]
@patrickjahns Tarball is QA-ready
