### ISSUE TITLE
Create acceptance tests for activity+groups

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/activity#740]
Based on the fix in https://github.com/owncloud/activity/pull/738 it would be great to have more tests that also add/delete groups // add/delete users and confirm that activity works as expected

**Comment by phil-davis** [comment]
PR #743 added test scenarios where a user or group is deleted and checked that, from the point-of-view of the remaining users, the previous actions with the deleted user/group can still be displayed.

When a user is deleted, they have a history of their actions. Presumably and administrator might want to review the history of activities of that user.

Is that a feature of the activity app?

If so, then we need to have tests that:
1) create a user
2) as that user, do some activity
3) as administrator, delete the user
4) as administrator, view the old activity of the deleted user

**Comment by dpakach** [comment]
@phil-davis I have addes one scenario for the above mentioned comment in https://github.com/owncloud/activity/pull/823 . Looks like as administrator we cannot see all the activity of the user. Only some e.g. creating a new tag is visible to the administrator.
Any more scenarios we can add in this case?

**Comment by phil-davis** [comment]
Assigned myself to review what is needed here, if anything.

**Comment by phil-davis** [comment]
The activity app is intended to be for users to see their own activity, not for admins to also be able to view user activity. So only user actions that have system-wide effects are visible in the admin activity list - creating a tag. There is not really anything else "system wide" that an ordinary user can do - they can't create/delete users/groups, can't change group membership...

So after a user is deleted, their activity data is also gone - which is fine.

The admin_audit app is the place where an admin can find history of deleted users...

So there are no more tests to write here.
