### ISSUE TITLE
Activity 2.5.1

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/activity#746]
### Reason
- Release needed for #744 
- Release needed for #769 

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Check/adapt info.xml stuff
- [x] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan @davitol https://github.com/owncloud/activity/issues/780

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable) @davitol 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [ ] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by davitol** [comment]
Closing the tickeet due to app was released  Jun. 21th 2019

**Comment by patrickjahns** [comment]
@davitol 
you've reached the wrong one - 2.5.0 was released in June https://github.com/owncloud/activity/issues/739

 2.5.1 is pending

**Comment by davitol** [comment]
RC Tarball is QA-ready @micbar
