### ISSUE TITLE
v2.5.1 Testplan

### ISSUE THREAD

**Issue by micbar** [owncloud/activity#780]
## 'Activity' Test Plan

- Run Testplan with all checked notifications in Activity settings menu and a mail set in our oC server.

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable Activity app via CLI using ```occ app:enable activity``` | The apps gets enabled | ✅  |
Disable Activity app via CLI using ```occ app:disable activity``` | The apps gets disabled | ✅  |
**All activities section** |  |   |
|  |   |
Check that all activities done in this Testplan are shown in this section |  | ✅  |
**Activities by you section** |  |   |
|  |   |
Check that all activities done with my user in this Testplan are shown in this section |  | ✅ |
**Activities by others section** |  |   |
Check that all activities done dealing with my user by other users in this Testplan are shown in this section |  |  ✅  |
An LDAP user shares a file with my user | Check that LDAP username is shown properly in this section | ✅  |
An LDAP user edits a file shared with my user | Check that LDAP username is shown properly in this section | ✅  |
A Shibboleth user shares a file with my user | Check that Shibboleth username is shown properly in this section | ✅  |
A Shibboleth user edits a file shared with my user | Check that Shibboleth username is shown properly in this section | ✅  |
**Favorites section**|  |   |
|  |   |
Make favorite a file | Check that the notification is shown in activity section and in the sidebar | ❌   |
Make favorite a folder | Check that the notification is shown in activity section and in the sidebar | ❌   |
**Comments**|  |   |
|  |   |
Make a comment in a file | Check that the notification is shown in activity section and in the sidebar | ✅  |
Make a comment in a folder | Check that the notification is shown in activity section and in the sidebar | ✅  |
**Shares section**|  |   |
|  |   |
Share a file/folder | Check that the notification is shown in activity section and in the sidebar| ✅  |
Share a file/folder with a user of other oC server | Check that the notification is shown in activity section and in the sidebar| ✅  | showing when the folder is accepted |
Share a file/folder via link | Check that the notification is shown in activity section and in the sidebar| ✅  |
Receive a share for another user| Check that the notification is shown in activity section and in the sidebar| ✅  |
Receive a share for another user of other oC server| Check that the notification is shown in activity section and in the sidebar| ✅ |
Receive a file/folder via link adding to your owncloud| Check that the notification is shown in activity section and in the sidebar| :x:  | #800 |
**Settings section stream**|  |   |
|  |   |
Uncheck a new file or folder has been created stream notification and create a folder| Notification is not shown | ✅  |
Uncheck a file or folder has been changed stream notification and change a file| Notification is not shown |  ✅  |  |
Uncheck limit notifications about creation and changes to your favorite files stream  notification and change favorite file and a regular file| Notification is not shown | :x:  | #799 |
Uncheck a file or folder has been deleted stream  notification and delete a file | Notification is not shown | ✅ |
Uncheck a file or folder has been restored stream  notification  and restore a file | Notification is not shown | ✅  |
Uncheck a file or folder has been shared stream  notification  and share a file| Notification is not shown  | ✅  |
Uncheck a file or folder was shared from another server stream  notification and accept a share | Notification is not shown | ✅  |
Uncheck a public shared file or folder was downloaded stream  notification and download a file | Notification is not shown |✅  |
Try to uncheck comments for files (always listed in stream) stream  notification and make a comment | It should not be possible | ✅ |
Uncheck System tags for a file have been modified stream  notification and tag a file|  Notification is not shown| ✅  |
Uncheck list your own file actions in the stream | Notifications are not shown| :x:  | #798 |
**Settings section mail**|  |   |
Uncheck a new file or folder has been created mail notification and create a file|  | ✅  |
Uncheck a file or folder has been changed mail notification and change a folder|  | ✅  |
Check limit notifications about creation and changes to your favorite files mail notification and change favorite file and a regular file| Only notifications about favorite files are sent | ❌   | https://github.com/owncloud/activity/issues/799
Uncheck a file or folder has been deleted mail notification and delete a folder |  | ✅ |
Uncheck a file or folder has been restored mail notification and restore a file | The notification is not sent to the mail| ✅  |
Uncheck a file or folder has been shared mail notification and share a file | The notification is not sent to the mail | ✅ |
Uncheck a file or folder was shared from another server mail notification and accept a share |  The notification is not sent to the mail | ✅  |
Uncheck a public shared file or folder was downloaded mail notification and download a file  |  The notification is not sent to the mail | ✅  |
Try to uncheck comments for files mail notification and make a comment | The notification is not sent to the mail| ✅  |
Uncheck System tags for a file have been modified mail notification and tag a file |  The notification is not sent to the mail | ✅ |
Uncheck notify about your own actions via email | Notifications are not sent to the mail | ✅  |
**webUI with several browsers**|  |   |
Check that notifications are shown properly using Safari as browser|  | ✅   |
Check that notifications are shown properly using Chrome as browser|  | ✅  |
Check that notifications are shown properly using Firefox as browser|  | ✅  |
Check that notifications are shown properly using IE 11 as browser|  | ✅ |
Check that notifications are shown properly using Edge as browser|  | ✅  |

**Comment by davitol** [comment]
Changelog:
- [ ] URL Formatter  https://github.com/owncloud/activity/pull/744

**Comment by micbar** [comment]
done
