### ISSUE TITLE
assigning a new tag to an image file does not show the correct preview in the stream

### ISSUE THREAD

**Issue by individual-it** [owncloud/activity#797]
### Steps to reproduce
1. add a tag to an png file
2. check activity stream

### Expected behaviour
preview should be shown

### Actual behaviour
![image](https://user-images.githubusercontent.com/2425577/67383586-262bd700-f5af-11e9-84e6-d76ff1facb7f.png)

**Comment by davitol** [comment]
DUpe of https://github.com/owncloud/activity/issues/646 ?
