### ISSUE TITLE
when no favorites are defined "Limit notifications about creation and changes to your favorite files" has no effect

### ISSUE THREAD

**Issue by individual-it** [owncloud/activity#799]
### Steps to reproduce
1. get rid of all favorites you have
1. enable "Limit notifications about creation and changes to your favorite files"
1. do changes to files
1. check activity stream

### Expected behaviour
files changes should not be listed

### Actual behaviour
file changes are listed

**Comment by davitol** [comment]
Kind of dupe of: https://github.com/owncloud/activity/issues/687 ?

**Comment by individual-it** [comment]
closing as there should be a decision about #687 first
