### ISSUE TITLE
Activity 2.5.2

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/activity#816]
### Reason

- Release needed for https://github.com/owncloud/enterprise/issues/3601

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "2.5.2 Testplan" @davitol https://github.com/owncloud/activity/issues/817

### Documentation

- [x] Changes in the docs needed? Yes for #811 

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [ ] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [ ] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by micbar** [comment]
@HanaGemela DEV done.

**Comment by micbar** [comment]
@davitol RC1 is ready https://github.com/owncloud/activity/releases/tag/v2.5.2RC1

**Comment by micbar** [comment]
@MarWeb88 You can see the progress to the final release here in this ticket.

**Comment by davitol** [comment]
> @davitol RC1 is ready https://github.com/owncloud/activity/releases/tag/v2.5.2RC1

@HanaGemela @jnweiger @micbar Tarball is QA ready

**Comment by HanaGemela** [comment]
@MarWeb88 Release done
