### ISSUE TITLE
acceptance tests sometines fail to login on drone

### ISSUE THREAD

**Issue by phil-davis** [owncloud/activity#822]
e.g.
https://drone.owncloud.com/owncloud/activity/1022/16/10
https://drone.owncloud.com/owncloud/activity/1021/36/14
https://drone.owncloud.com/owncloud/activity/1020/15/10
and look back further in the drone history.

There are a lot of times when the Behat acceptance test does not find the login page.

Maybe there is something slow in the Apache server getting started? Or some other timing problem?

This app is using the same `.drone.star` as other apps, so why is it behaving differently.

Note: This app will be the first to start each night, so it always gets allocated on new drone agents that have to pull each docker image... So maybe it is the most likely to see timing problems.

**Comment by kiranparajuli589** [comment]
@phil-davis is this issue fixed by #https://github.com/owncloud/admin_audit/pull/287

**Comment by phil-davis** [comment]
I think that I have seen this problem since the "wait for Apache server" changes.
But it has not happened for quite a while - the last 19 nightly jobs have all passed.

Closing - we are not going to be able to reproduce this.
