### ISSUE TITLE
EmailNotification background job stops at send failure

### ISSUE THREAD

**Issue by kulmann** [owncloud/activity#840]
### Steps to reproduce
1. Log in to ownCloud
2. Enable mail notifications for created/changed folders
3. Enable sending mail notifications to yourself
4. Set an invalid email address of a valid mail host for your logged in user (e.g. deactivated account)
5. Change files in a way that activity notifications are triggered
6. Observe, that the email can't  be send and all other mails after it in the activity mail queue remain untouched.

### Expected behaviour
On failure of a single mail, the background job should continue with other mails.

### Actual behaviour
Background job dies on a failed email send attempt.

Identified the issue here:
https://github.com/owncloud/activity/blob/4820245648fc384965f377bbef24bc4e61bdfc5a/lib/BackgroundJob/EmailNotification.php#L150

EmailNotification job throws the exception instead of logging it and continuing with the other emails. As we have the `$logger` available we could do just that. But as I don't have good insights to the activity app I would like to hear some more thoughts on this before I make this 1 line PR (`$this->logger->logException($e, ['app' => 'activity'])`. Also I would like to enhance this https://github.com/owncloud/activity/blob/4820245648fc384965f377bbef24bc4e61bdfc5a/lib/BackgroundJob/EmailNotification.php#L132 by adding a check if the user is active at all.

**Comment by VicDeo** [comment]
Ok, but as it is not possible to detect the reason of failure properly   we will get 200 log entries for the whole batch if a **sender** email is misconfigured

**Comment by VicDeo** [comment]
Here we go https://github.com/owncloud/activity/pull/842

**Comment by VicDeo** [comment]
dev is done
