### ISSUE TITLE
Activity 2.6.0 (also 2.5.x) not getting Mail Notifications anymore

### ISSUE THREAD

**Issue by maddinq** [owncloud/activity#892]
after changing files (upload, download, deleate) I'm calling the cron manually but no mail was sent.
My settings (admin, mail notifications for all actions enabled). but I and the rest of the team not getting Mails since 01 Oct. 2020 anymore.

**Comment by maddinq** [comment]
Mail Service is working, test mail is getting through. 
Steps from https://doc.owncloud.com/server/admin_manual/configuration/server/activity_configuration.html are all made. and it worked before

**Comment by micbar** [comment]
@maddinq I tested it yesterday with `master` works fine.

can you check your background jobs?

```
 php occ  background:queue:status
+--------+----------------------------------------------------+---------------------------+---------------+
| Job ID | Job                                                | Last Run                  | Job Arguments |
+--------+----------------------------------------------------+---------------------------+---------------+
| 1      | OCA\Files\BackgroundJob\ScanFiles                  | 2020-10-14T14:27:11+00:00 |               |
| 2      | OCA\Files\BackgroundJob\DeleteOrphanedItems        | 2020-10-14T14:27:12+00:00 |               |
| 3      | OCA\Files\BackgroundJob\CleanupFileLocks           | 2020-10-14T14:28:13+00:00 |               |
| 4      | OCA\Files\BackgroundJob\CleanupPersistentFileLocks | 2020-10-14T14:28:44+00:00 |               |
| 5      | OCA\DAV\CardDAV\SyncJob                            | 2020-10-14T14:28:51+00:00 |               |
| 6      | OCA\DAV\BackgroundJob\CleanProperties              | 2020-10-14T14:29:04+00:00 |               |
| 7      | OCA\Federation\SyncJob                             | 2020-10-14T14:29:04+00:00 |               |
| 8      | OCA\Files_Sharing\DeleteOrphanedSharesJob          | 2020-10-14T14:29:04+00:00 |               |
| 9      | OCA\Files_Sharing\ExpireSharesJob                  | 2020-10-14T14:29:04+00:00 |               |
| 10     | OCA\Files_Sharing\External\ScanExternalSharesJob   | 2020-10-14T14:29:04+00:00 |               |
| 11     | OCA\Files_Trashbin\BackgroundJob\ExpireTrash       | 2020-10-14T14:29:04+00:00 |               |
| 12     | OCA\Files_Versions\BackgroundJob\ExpireVersions    | 2020-10-14T14:26:16+00:00 |               |
| 13     | OCA\UpdateNotification\Notification\BackgroundJob  | 2020-10-14T14:26:21+00:00 |               |
| 14     | OCA\Activity\BackgroundJob\EmailNotification       | 2020-10-14T14:31:29+00:00 |               |
| 15     | OCA\Activity\BackgroundJob\ExpireActivities        | 2020-10-14T14:26:26+00:00 |               |
| 16     | OC\Authentication\Token\DefaultTokenCleanupJob     | 2020-10-14T14:32:28+00:00 |               |
| 19     | OCA\OAuth2\BackgroundJob\CleanUp                   | 2020-10-14T14:28:31+00:00 |               |
+--------+----------------------------------------------------+---------------------------+---------------+
```

You can check the last run date of `OCA\Activity\BackgroundJob\EmailNotification `

**Comment by maddinq** [comment]
Unfortunately I have the system running on a shared hosting system. Any suggestions?

**Comment by DeepDiver1975** [comment]
> Thank you for your reply. Unfortunately I have the owncloud running on a shared hosting system. Any suggestions?

select * from oc_jobs

**Comment by maddinq** [comment]
OCA\Activity\BackgroundJob\EmailNotification | null | 1602723601 | 1602723601 | 0 | 3

**Comment by maddinq** [comment]
when I manually call the webcron - its not changing

**Comment by DeepDiver1975** [comment]
It was executed last at 2020-10-15T01:00:01+00:00 (1602723601)

So cron is working ....

please check your personal settings about activiy - 

![Screenshot from 2020-10-15 13-13-25](https://user-images.githubusercontent.com/1005065/96116112-3e93b080-0ee8-11eb-85b1-b1ec386cd100.png)

**Comment by maddinq** [comment]
I can confirm the settins, even when I select "hourly" nothing happens for me and all other users. 
The last time that the mail was sent out was 01.10.2020 (in our mailbox). and of course we changed files. so very strange

**Comment by micbar** [comment]
ok. We need to go further...

Can you access the `ownclod.log` file?
Default location is in the data folder (where all user home folders are located).

**Comment by maddinq** [comment]
yes, its 17MB -should we move to different chat than github?

**Comment by micbar** [comment]
We are entering support mode now ;-)

OpenSource Support is central.owncloud.org

**Comment by maddinq** [comment]
Okay, so should I open a ticket there and referrer to our chat?

**Comment by maddinq** [comment]
Update: for some reason it worked a few days, than again not! Still not working. Any further idea?

**Comment by maddinq** [comment]
cron execution - works perfect
mail sending (general) - works perfect
but no one is getting the activity notifications

**Comment by maddinq** [comment]
I tried "php ./occ activity"
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 106958848 bytes) in /www/htdocs/owncloud/lib/private/Log/Owncloud.php on line 117

**Comment by maddinq** [comment]
Looks like the whole activity thing needs too much memory within the Terminal, maybe thats also the problem, why its not running in the web-service as well ? What could be the reason (web has 650mb memory_limit)

**Comment by maddinq** [comment]
After increasing the Memory Limit much more - I'm getting:
PHP Fatal error:  Allowed memory size of 681574400 bytes exhausted (tried to allocate 187403408 bytes) in /www/htdocs//lib/composer/swiftmailer/swiftmailer/lib/classes/Swift/Plugins/LoggerPlugin.php on line 122

**Comment by micbar** [comment]
you ned to check which php setting is needed for the php-cli

**Comment by micbar** [comment]
The web service is out of this context. The activity is sent from the background cron process on the system itself. Therefore it uses php-cli. On some distros, php has different configs for apache and cli

**Comment by maddinq** [comment]
PHP - I used for the terminal 7.2 with 550-650MB memory_limit but its always not ending good...lot of logs and errors like described above. 
But so or so it should run normally via the web.. but it's not doing it. Any further idea how to solve this issue?

**Comment by micbar** [comment]
you can get an idea of the size of the pending messages with the following DB query `SELECT count(*) FROM oc_activity_mq;`

**Comment by micbar** [comment]
500 MB by the way is not much for php cli. Try 2GB or unlimited.

**Comment by micbar** [comment]
> But so or so it should run normally via the web..

What does that mean? Activity mails are not triggered from the web-service.

**Comment by maddinq** [comment]
1) `SELECT count(*) FROM oc_activity_mq` -> count(2530)
sound a bit much, can I clear it somehow and start "fresh" from today?
2) its a shared hosting system...I don't get more that the 750mb RAM memory_limit, 2GB is impossible right now
3)Result is we don't get any notifications since weeks (it worked for 2-3 days) than again not and still not.

**Comment by maddinq** [comment]
so can I somehow clear the queue and start "fresh" ?

**Comment by JanAckermann** [comment]
@maddinq You can clear the database table for a "fresh start".
Please reopen if the error is still existent.
