### ISSUE TITLE
Activity 2.6.0

### ISSUE THREAD

**Issue by micbar** [owncloud/activity#894]
### Reason

- Release needed for #893 

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] ??? Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] ??? Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "2.6.0" Testplan @davitol  https://github.com/owncloud/activity/issues/895

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date) -- check for missing entries too.

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol https://github.com/owncloud/activity/issues/895

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by micbar** [comment]
@MarWeb88 you need this for a customer.

**Comment by jnweiger** [comment]
@MarWeb88 https://github.com/owncloud/activity/releases/tag/v2.6.0RC1 is available for testing

**Comment by jnweiger** [comment]
release deadline: 2020-11-23

**Comment by davitol** [comment]
> @MarWeb88 https://github.com/owncloud/activity/releases/tag/v2.6.0RC1 is available for testing

@jnweiger Tarball is QA ready LGTM
