### ISSUE TITLE
[strictly 10.8.0]  Activity 2.6.1

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/activity#943]
# Release 2.6.1

### Reason
Release needed for
* Automations in activity stream https://github.com/owncloud/activity/pull/942
* Add shareExpire-param to indicate if a share was removed due to its expiry https://github.com/owncloud/activity/pull/944

### Requirements
* owncloud 10.8

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) https://github.com/owncloud/activity/issues/964
- [x] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [x] Changelog testing
    - [x] Manual testing #942
    - [x] Manual testing #944  
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [ ] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10-0)  and [new portal](https://portal.owncloud.com) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

### Aftermath 
**Important** 
After release restore server part in drone config, see:
https://github.com/owncloud/activity/pull/942/files/b8324ebd49fd1b8d96bd204d2b857eec1393f479

**Comment by micbar** [comment]
RC1 in https://github.com/owncloud/activity/releases/tag/v2.6.1RC1

**Comment by micbar** [comment]
RC2 with updated core minimum version constraint. https://github.com/owncloud/activity/releases/tag/v2.6.1RC2

**Comment by JanAckermann** [comment]
@micbar RC3 needed with #967

**Comment by micbar** [comment]
RC3 done https://github.com/owncloud/activity/releases/tag/v2.6.1RC3

**Comment by jnweiger** [comment]
### Issues opened while testing
* [ ] #969
* [ ] #970
* [ ] #971

**Comment by jnweiger** [comment]
Download:    https://github.com/owncloud/activity/releases/tag/v2.6.1
Marketplace: https://marketplace.owncloud.com/apps/activity
