### ISSUE TITLE
Add acceptance tests for share expiration activity entries

### ISSUE THREAD

**Issue by phil-davis** [owncloud/activity#968]
There have not been any automated tests for what happens after a link or share expires, because it was difficult to "wait until tomorrow"  in CI for a link or share to reach its expiry.

But now we have a step in core:
`When the administrator expires the last created share using the testing API`
or
`Given the administrator has expired the last created share using the testing API`

That is supported by the testing app, which sets the expiration date of the share to yesterday. Then tests can access the share, and the server automatically detects that the share expires and removes it.

We can use that to add automated tests for share expiration messages in the activity app.

Add scenarios to test the activity messages that happen when user, group, link and federated shares expire.

**Comment by kiranparajuli589** [comment]
@phil-davis there are already check for the activity messages for these type of shares

user share: https://github.com/owncloud/activity/blob/master/tests/acceptance/features/apiActivity/list.feature#L703
group share: https://github.com/owncloud/activity/blob/master/tests/acceptance/features/apiActivity/list.feature#L747
link share: https://github.com/owncloud/activity/blob/master/tests/acceptance/features/apiActivity/list.feature#L802

did the issue mean these types of scenarios? if yes, we only need to add tests for the fed share expiration.

**Comment by phil-davis** [comment]
@kiranparajuli589 yes, it looks like most test cases were covered in PR #973 

If someone can make a scenario for a federated share expiration, that would be good. It will need to go in a test suite that has a CI pipeline with a federated server running.

**Comment by grgprarup** [comment]
> @kiranparajuli589 yes, it looks like most test cases were covered in PR #973
> 
> If someone can make a scenario for a federated share expiration, that would be good. It will need to go in a test suite that has a CI pipeline with a federated server running.

The scenario to check the activity list after the share was expired for federated share is added in this PR (https://github.com/owncloud/activity/pull/1115). But in the case of federated share, we cannot see any activity related to share expired added in activity list like in user share, group share, and public link share. @phil-davis any idea what to do?

**Comment by phil-davis** [comment]
> any suggestions on what to do?

issue #1117 was raised for that problem.

Closing this issue because the test are done and merged.
