### ISSUE TITLE
[QA] Activity when receiving a federated share is missing in sidebar and `Activities by others`

### ISSUE THREAD

**Issue by JammingBen** [owncloud/activity#970]
### Steps to reproduce
1. Receive and accept a share from a federated OC system
2. Check the sidebar and you activity stream

### Expected behaviour
The activity should be listed in the file sidebar and in the activity stream in `Activities by others`

### Actual behaviour
The activity is missing in the file sidebar as well as in `Activities by others`

**Comment by JanAckermann** [comment]
As in #623
